- client/package-lock.json
- package.json
> fix(npm install): 'npm install' was added for running client or server

- package.json
- fixed postinstall script to also work on mac
- Closes #20
> fix(packagejson)

- .github/workflows/test_prs.yml
- use specific version of action instead of @master
> fix(pr-actions)

- client/src/components/App/AppToolbar/TopToolbar/TopToolbar.tsx
- client/src/components/App/Content/LandingPage/LandingPage.tsx
- client/src/index.tsx
- client/src/models/User.ts
- client/src/redux/User/userActionCreatores.ts
- client/src/redux/User/userActionTypes.ts
- client/src/redux/User/userReducer.ts
- client/src/redux/rootReducers.ts
- client/src/redux/store.ts
- client/src/redux/storeStateType.ts
- package-lock.json
- package.json
Added redux ans user model.
On Identification we will have to setUser.
> feat(Add Redux): added redux

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.test.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfoStyles.ts
> fix(static info bar)

- server/src/ClientToDBAPI/mainRoute.ts
- server/src/middlewares/Authentication.ts
> logging(Auth) - added cookie-loggin auth middleware to debug stuff

- client/src/components/App/Content/InvestigationForm/InvestigationForm.test.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- client/src/models/City.ts
- client/src/redux/City/cityActionCreators.ts
- client/src/redux/City/cityActionTypes.ts
- client/src/redux/City/cityReducer.ts
- client/src/redux/rootReducers.ts
- client/src/redux/storeStateType.ts
- server/src/ClientToDBAPI/Address/mainRoute.ts
- server/src/ClientToDBAPI/mainRoute.ts
- server/src/DBService/Address/Query.ts
- server/src/Models/Address/City.ts
- server/src/Models/Address/Street.ts
Added cities to redux, loaded from db on personal info tab .
cities map includes : key=city id, value=city object(city id+display name)
> feat(Cities redux): Added cities to redux

- client/src/commons/CheckBox/CustomCheckbox.tsx
- client/src/commons/FormRowWithInput/FormRowWithInput.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InfoItem.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InfoItemWithIcon/InfoItemWithIcon.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationMetadata/InvestigationMetadata.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/ContactDateCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/NewInteractionEventDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
Automation locators were added to almost every application component (`test-id` attributes) in order to have a simpler and easier automated testing development. 
**This is very crucial for us so we can have automation developed quickly.**
- Added ids to ExposureForm
- Added ids to FlightsForm
- Added ids to ExposuresAndFlights
- Added optional id field to interface FormRowWithInputProps 
- Added optional id property to InfoItem
- Added optional id property to InfoWithIcon
- Added ids to InvestigationMetadata
- Added ids to InvestigationForm
- Added optional id property to CustomCheckbox
- Added ids to PersonalInfoTab
- Added Ids to clinical details 
- Added IDs to ContactDateCard
- Added IDs to InteractionEventForm
- Added IDs to NewInteractionEventDialog
> Feat(automation locators)

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
Fixed attribute error (testId not assignable).
> fix/InvestigatedPersoninfo testId error

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/EditInteractionEventDialog/EditInteractionEventDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/EditInteractionEventDialog/EditInteractionEventDialogInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/EditInteractionEventDialog/useEditInteractionEventDialog.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/NewInteractionEventDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/NewInteractionEventDialogInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/useNewInteractionEventDialog.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTabInterfaces.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/DBService/ContactEvent/Mutation.ts
- server/src/DBService/ContactEvent/Query.ts
- server/src/Models/ContactEvent/GetContactEvent.ts
getting the update contact event mutations to work and the ui to be synced with the db actions
>  Fix/contact-events-mutations

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCard.tsx
- fixed bug that prevented address from showing in a contact-event
> fix(contact event)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/EditInteractionEventDialog/useEditInteractionEventDialog.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
-Changes that were made to contact event now saved to the db
> fix(update-contact-event):

- server/src/middlewares/Authentication.ts
> fix(auth): case sensitive linux

- client/src/Utils/axios.ts
- client/src/Utils/displayUtils.ts
- client/src/commons/AutoCompletedField/AutoCompletedFieldTypes.ts
- client/src/commons/AutoCompletedField/AutocompletedField.tsx
- client/src/commons/Contexts/ExposuresAndFlights.ts
- client/src/commons/DatePick/DatePickStyles.ts
- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationFormInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- client/src/models/ExposureData.ts
- client/src/models/FlightData.ts
This pull requet:
* change the tab to the relevant interface
* connect the form to db
This branch is copy of the previous branch
> feat(exposuresAndFlights): done

- client/src/commons/Contexts/ExposuresAndFlights.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
- client/src/models/ExposureData.ts
- client/src/models/FlightData.ts
This pr fixes bug #223 - loading exposures and flights tab doesn't load the date pickers exisiting data
> fix(exposuresAndFlights) : exposures and flights dates are now loaded #223

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> Add custom title font for swal phone call error

- client/src/commons/AutoCompletedField/AutoCompletedFieldTypes.ts
- client/src/commons/AutoCompletedField/AutocompletedField.tsx
- client/src/commons/CircleSelect/CircleSelect.tsx
- client/src/commons/CircleSelect/CircleSelectStyles.ts
- client/src/commons/CircleTextField/CircleTextField.tsx
- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
- client/src/commons/PhoneNumberTextField/PhoneNumberTextField.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
*add require option and design on selectFields
*add require option and design on textFields
> fix:(add required indication on required fields bug #240) 

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
The bug was caused by the fact that every change on date pick triggered an onChange event. to fix it I changed every value of date pick to defaultValue and update it's value onBlur instead of change
(some changed were caused by prettier, changes to review are on DatePick components)
> fix(datePick) : fixed - changing date data

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.test.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTabInterfaces.ts
- server/src/ClientToDBAPI/ClinicalDetailsRoute/mainRoute.ts
- server/src/ClientToDBAPI/LandingPageRoute/mainRoute.ts
- server/src/DBService/ClinicalDetails/Query.ts
- server/src/Models/ClinicalDetails/CoronaTestDateQueryResult.ts
Now dates displayed according to symptoms status
> fix(investigation dates):

- client/package-lock.json
- client/package.json
- client/src/commons/DatePick/DatePickStyles.ts
- client/src/commons/DatePick/TimePick.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/index.tsx
This pull request switches the use of textfield with type date/time into mui's pickers
(new pr)
> feat(date-picker): use material-ui date picker

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/AddressGrid/AddressGrid.tsx
fixed address grid to match actual json in db
> fix - address grid

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/AddressGrid/AddressGrid.tsx
- fixed address grid typeError
- removed entrance and floor display ing grid since they arent saved in db
> fix(fix(contacts)) fixed address grid

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/BusinessContactForm/BusinessContactForm.tsx
- Added two more `test-id` attributes to the buisness contact form fields
> feat(buisnessContactForm automation locators)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/AddressGrid/AddressGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/DefaultPlaceEventGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/HospitalEventGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/OtherPublicLocationGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/SchoolEventGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/EditInteractionEventDialog/useEditInteractionEventDialog.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/AddressForm/AddressForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/DefaultPlaceEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/HospitalEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/OtherPublicLocationForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/SchoolEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsEventDialogContext/InteractionEventAddressFields.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/useNewInteractionEventDialog.ts
- client/src/models/Address.ts
- changed type to remove unused properties and match google gecode api as saved in db currently
- refactored code to match new definition
- **those changes fixed bug in editing a contact event**
> fix(contact event) location types

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
Changing time using keyboard with time picker will only override hours and minutes of current date
> fix(time-picker)

- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/TransportationAdditionalGrids/FlightEventGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/BusEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/FlightEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/TrainEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsEventDialogContext/InteractionEventDialogFields.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/models/Address.ts
- db scripts/Contact_functions/delete_contact_event_function.sql
- db scripts/Contact_functions/update_contact_event_function.sql
- db scripts/Contact_functions/update_contact_person.sql
- Displaying contacts events' with placeType transportaion as they are should
- Fixing the crash when moving to clinical details tab
- Documenting changes and additions of db functions
> fix(contact events): fixed bugs regarding to the contact event flow

- client/src/commons/LocationInputField/useGoogleApiAutocomplete.ts
- fixed parsing by adding another couple of try/catch clauses
- added console error logs for when all parsing attempts fail
> fix(parsing)

- client/src/commons/FormInput/FormInput.tsx
Added an id for all of the FormInputs, necessary for easy automation locators.
> feat(FormInput test attribute)

- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/SchoolEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
Added `test-id` to new Select elements.
> feat(Select test locators)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTabStyles.ts
fixed white spaces in personal info tab and clinical details
> fix(white spaces)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlightsStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInputStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightFormStyles.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTabStyles.ts
-Fixed spacing in ExposuresAndFlights tab, also fixed bug #330
> fix(spacing between text fields and labels - ExposuresAndFlights):

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.test.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTabInterfaces.ts
the last investigation date is the current date (approved by tal)
> fix(dates to investigate):

- client/azure-client-pipeline.yml
- server/azure-server-pipeline.yml
- test and master are now pushed also to MOH container registry
> fix(images): fixing ci cd pipelines to push images

- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/AddressForm/AddressForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/AddressForm/AddressFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/BusinessContactForm/BusinessContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/BusinessContactForm/BusinessContactFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/DefaultPlaceEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/DefaultPlaceEventForm/DefaultPlaceEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/DefaultPlaceEventForm/DefaultPlaceEventFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/HospitalEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/MedicalLocationForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/OfficeEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/OtherPublicLocationForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/SchoolEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/BusEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/FlightEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/TrainEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/TransportationFormsStyles.ts
- client/src/styles/formStyles.ts
-InteractionEventForm and all of the subforms are now refactored to be "prettier"
> fix(InteractionEventForm and subforms):

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
Fixed parameter name for two test locators.
> fix(clinical details automation locators)

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInputStyles.ts
- client/src/index.css
- client/src/styles/theme.ts
- fixed bug 366
- fixed bug 318
- fixed bug 359
> fix(ui): fixed ui issues

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
> fix(ContactQuestioningPersonal): fixed default birth date and allowed erasing

- client/src/commons/DatePick/DatePick.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
Added a condition to display calender with years
> fix(birth date calender):

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
*Cant enter future date for hospitalization start or end date
*Fixed date validation error
> fix(future-date-validation) - add validation on hospitalization

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
*Cant enter future date for isolation start or end date
> fix(future-date-isolation-validation) - add validation on isolation

- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationFormInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTabInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- fixed initial contact questioning tab state
- fixed contact questioning tab name display update
> fix(contact questioning tab): fixed bugs 382 & 387

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/EditInteractionEventDialog/EditInteractionEventDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/NewInteractionEventDialog.tsx
> fix(InteractionEventForm): fixed invalid time saved when creating an event

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/BusEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/FlightEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/TrainEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/TransportationFormsStyles.ts
- fixed transportation bus event form
- fixed transportation flight event form
- fixed transportation train event form
> fix(new transportation event): fix UI

- client/src/commons/Contexts/ClinicalDetailsContext.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/models/Contexts/ClinicalDetailsContextData.ts
- client/src/models/enums/ClinicalDetailsFields.ts
added the boolean fields to the schema and the fields
> fix(unknown symptoms start date):

- client/src/commons/DatePick/DatePick.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
-now all future dates in the symptoms start date pick are disabled
-also added try catch in getDatesToInvestigate
> fix(future symptoms start date crash):

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventSchema.ts
- client/src/models/Contact.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
For now I changed phone number to be unrequired.
In the future phone number is going to be required again and save interactions will be possible even if the form isn't valid,
but finish investiogation will be impossible
>  fix(interactionsForm): change phone number to be

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
for city name and contact container
> Added important automation locators

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
Solves [bug 420](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/420) for end date being invalid when selecting today.
> fix(clinical) change future date validation to be start of tomorrow

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
Bug 391 solved
error showing when date is invalid
> show error when date is invalid

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
Fixes [bug 441](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/441/) showing long english errors in house number and floor when values are null.
> fix(clinical) fix issue with displaying errors in english

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/BusinessContactForm/BusinessContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/BusinessContactForm/BusinessContactFormStyles.ts
Fix bug [426](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/426/)
> Fix(interactions contact info) - fix contact info UI

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
> fix(missing date pick automation locator)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
fix bug [453](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/453/)
> Fix(clinical details isPregnant) - is pregnant will only show for a female

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- server/src/DBService/ClinicalDetails/Query.ts
contacted people loading is now conditional
> Fix(contacted people loading)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsStyles.ts
> fix(ClinicalDetails.tsx): remove the collapse that destroyed the css

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningStyles.ts
- added empty option in family relationship select
> fix(contact questioning)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsStyles.ts
> fix(ClinicalDetails.tsx): remove collapse conditioning that screwd css 

- client/src/commons/AutoCompletedField/AutoCompletedFieldTypes.ts
- client/src/commons/AutoCompletedField/AutocompletedField.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInput.tsx
Fixes bug [495](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/495/)
> fix(flights country label) - add label and placeholder for country in airport input

- client/src/commons/AutoCompletedField/AutoCompletedFieldTypes.ts
- client/src/commons/AutoCompletedField/AutocompletedField.tsx
- client/src/commons/LocationInputField/LocationInput.tsx
- client/src/commons/LocationInputField/useGoogleApiAutocomplete.ts
- client/src/commons/Map/Map.tsx
- fixed to fetch addressed even without commas
- remove IL comp restriction
> fix(google api autocomplete)

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
Fixes bug [497](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/497/)
> fix(investigationTable-sort-indication) - Add color indication when sort is active

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
Fixes bug [497](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/497/)
recommended reading material - https://material-ui.com/customization/components/#use-rulename-to-reference-a-local-rule-within-the-same-style-sheet
> fix(investigationTable-sorts-indication) - Add color indication when sort is active (without using !important)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/BackgroundDiseasesFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
Fixed missing locators in NumericTextField
> fix(missing-automation-locators)

- client/src/Utils/Address/AddressOptionsFilters.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/PlacesAdditionalForms/TransportationAdditionalForms/BusEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
> fix(city-sorting): add filter options for city and streets autocomplete

- client/package-lock.json
- server/src/ClientToDBAPI/CountiesRoute/mainRoute.ts
- server/src/ClientToDBAPI/LandingPageRoute/mainRoute.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/middlewares/Authentication.ts
Currently the county display name route is defined as an admin route which it shouldn't be. This PR makes it a normal route.
> fix(county) remove admin middleware from route

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.test.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/InvestigationTableRow.ts
- db scripts/groupInvestigationsSort.sql
display desk name on investigation name
> feat(desk name):

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
> fix(FlightsForm): switch order of starting point and destination

- client/src/commons/AlphabetTextField/AlphabetTextField.tsx
- client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
- client/src/commons/NumericTextField/NumericTextField.tsx
- client/src/commons/TypingPreventionTextField/TypingPreventionTextField.tsx
- client/src/commons/TypingPreventionTextField/TypingPreventionTextFieldTypes.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
-Added basic phone validation for phone field in contact questioning tab
> fix(ContactQuestioning phone text field):

- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- fix bug that made locations without a placename field appear empty
> Fix(interaction event) default place name

- client/src/components/App/App.tsx
- client/src/components/App/AppToolbar/useAppToolbar.tsx
- client/src/components/App/Content/SignUp/SignUpForm/SignUpForm.tsx
- client/src/components/App/Content/SignUp/SignUpForm/SignUpFormStyles.ts
- client/src/components/App/Content/SignUp/SignUpForm/useSignUpForm.ts
- client/src/models/enums/SignUpFields.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/middlewares/Authentication.ts
[575](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/recentlyupdated/)
> fix(signup): changed the sign up form structure and prevented swal from working

- client/public/index.html
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.test.tsx
- server/src/ClientToDBAPI/ContactedPeople/mainRoute.ts
* logs for contact questioning tab
* FINALLY the title has been changed!
> feat(contact questioning): add logs contacts questioning tab

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTabInterfaces.ts
- server/src/ClientToDBAPI/ClinicalDetailsRoute/mainRoute.ts
- added check to limit number of days to investigate
- removed unused state that uses non-existent property
> Fix(contact events) - old symptoms start crash

- server/src/middlewares/Authentication.ts
make signup work in dev environment
> fix(Authentication): add ? to check if user

- client/src/components/App/AppToolbar/IsActiveToggle/IsActiveToggleStyles.ts
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- server/src/Models/InvestigationMainStatus.ts
- server/src/middlewares/Authentication.ts
* added logs to end investigation flow
* change isActive toggle margin to vw instead of px
* add minWidth to isActive toggle buttons in order to create equal width (Ofek approved)
> feat(EndInvestigation): add logs to end investigation flow

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- fetch data only after user is updated
> fix(hopefully)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/usePersonalInfoTab.ts
handle null values in clinical details and personal details
> fix(null values):

- client/src/commons/AlphabetTextField/AlphabetTextField.tsx
- client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
- client/src/commons/NumericTextField/NumericTextField.tsx
- client/src/commons/TypingPreventionTextField/TypingPreventionTextFieldTypes.ts
* change type preventive text field interface 
* remove required from schema
> fix(delete-first-letter): now it possible to delete first letter

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/usePersonalInfoTab.ts
handle null values in different fields
> fix(clinical details validations):

- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
skip the validity check of contact quationing tab if he doesnt exist
> fix(finish-investigation-without-contacts): fixed

- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/Users/Query.ts
Get group users now filters non-active users
> feat(group) change get group users to find active group users

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/useInvestigatedPersonInfo.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- server/src/DBService/Users/Mutation.ts
**IMPORTANT**
- This PR requires immediate changes to DB prod and Schemas
> fix(): investigation status test

- client/src/commons/AutoCompletedField/AutoCompletedFieldStyles.ts
- client/src/commons/AutoCompletedField/AutocompletedField.tsx
- client/src/commons/FieldName/FieldName.tsx
- client/src/commons/FormRowWithInput/FormRowWithInput.tsx
- client/src/commons/FormTitle/FormTitle.tsx
- client/src/commons/FormTitle/FormTitleStyles.ts
- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
- client/src/commons/LocationInputField/LocationInputFieldStyles.ts
- client/src/commons/Map/Map.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/BackgroundDiseasesFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/HospitalFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/IsolationDatesFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/IsolationProblemFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningCheck.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/styles/formStyles.ts
- unified form appearance 
- added and modified existing generic form part components (as described below) 
- removed space below exposure source search 
- bolded main table text
<details>
<summary>FieldName</summary>
receives a title and sets a bolded field name in its simplest form
</details>
<details>
<summary>FormRowWithInput</summary>
receives field name and form-input children
represents a single full row in a form tab
</details>
<details>
<summary>FormTitle</summary>
largest typographic element to represent titular text in a tab
</details>
> Fix(ui) unified form ui

- client/src/components/App/AppToolbar/AppToolbar.tsx
- client/src/components/App/AppToolbar/AppToolbarStyles.ts
This PR adds navigation buttons that appear when admin or above and not currently in an investigation.
> feat(navButtons) add navigation buttons to home page and user management

- client/src/components/App/AppToolbar/AppToolbar.tsx
- client/src/components/App/AppToolbar/useAppToolbar.tsx
> fix(is-active-toggle): show toggle after user is loaded

- client/src/components/App/AppToolbar/AppToolbar.tsx
- client/src/components/App/AppToolbar/useAppToolbar.tsx
> fix(is-active): show toggle after user is loaded

- client/src/commons/FieldName/FieldName.tsx
- client/src/commons/FormRowWithInput/FormRowWithInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
נוצרת הודעת השגיאה יש לבחור מוסד רק במידה ויטענו רשימת המוסדות הרלוונטיים (בתיאום עם אופק) בנוסף מתקן את מיקום הכוכב של חקירה מורכבת בשדה גורם מבטח
> fix(Personal Info Tab): fix institution names border

- client/src/commons/Buttons/PrimaryButton/PrimaryButton.tsx
- client/src/commons/Buttons/PrimaryButton/PrimaryButtonStyles.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/Context/CommentContext.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/CommentDialog/CommentDialog.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/CommentDialog/CommentDialogStyles.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/InvestigationMenu.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/InvestigationMenuStyles.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
- client/src/models/InvestigationInfo.ts
- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- server/src/DBService/InvestigationInfo/Mutation.ts
- server/src/DBService/InvestigationInfo/Query.ts
- now users can comment on an inveastigation
- added ability to modify width and background color in button
> feat(comment)

- client/src/commons/AlphabetTextField/AlphabetTextFieldTypes.ts
- client/src/commons/NumericTextField/NumericTextFieldTypes.ts
- client/src/commons/TypingPreventionTextField/TypingPreventionTextField.tsx
- client/src/commons/TypingPreventionTextField/TypingPreventionTextFieldTypes.ts
- client/src/components/App/Content/SignUp/SignUp.tsx
- client/src/components/App/Content/SignUp/SignUpForm/SignUpForm.tsx
- client/src/components/App/Content/SignUp/SignUpForm/useSignUpForm.ts
- client/src/components/App/Content/UsersManagement/UserInfoDialog/UserInfoDialog.tsx
- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- client/src/models/SignUpUser.ts
- client/src/models/enums/CRUD.ts
- client/src/models/enums/FormMode.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/Users/Query.ts
[643](https://dev.azure.com/spectrumFactory/CoronaI/_backlogs/backlog/CoronaI%20Team/Features/?workitem=643)
> feat/user-info: display user information when clicking the person icon

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/ContactDateCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGridStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCardStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/useInteractionsForm.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTabInterfaces.ts
- client/src/models/Contact.ts
- client/src/models/enums/InteractionsEventDialogContext/InteractionEventContactFields.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/ClientToDBAPI/LandingPageRoute/mainRoute.ts
- server/src/DBService/ContactEvent/Mutation.ts
- server/src/Models/ContactEvent/Contact.ts
Added Schemas changes:
https://github.com/CoronaTeamMOD/CoronaISchemas/pull/1
> feat(): delete contacted person

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> fix(static investigation info)

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementStyles.ts
- client/src/components/App/Content/UsersManagement/UsersManagementTableHeaders.ts
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- client/src/models/enums/SortOrder.ts
[437](https://dev.azure.com/spectrumFactory/CoronaI/_backlogs/backlog/CoronaI%20Team/Features/?workitem=437)
> feat(sort): add sort option for users management

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- hide comment behind table header on scroll
> fix(investigation table)

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
> fix(bugs): fixed contact questioning, personal and investigation info

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/commentDisplay/commentDisplay.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/commentDisplay/commentDisplayStyles.ts
- fixed bug that prevented filters from being seen entirely
> fix(landing page)

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/CommentDialog/CommentDialog.tsx
- reset comment when closing without save
> fix (comment)

- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
[756](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/756/)
> fix(SortUsersManagement): hide sort label from specific cells and fix the sort direction

- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- combined the status and endTime mutation to one
> fix(end investigation mutation):

- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
[752](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/752/)
> fix(loadInvestigations): reload investigations after finishing one

- client/src/commons/AutoCompletedField/AutocompletedField.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/useInvestigatedPersonInfo.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/IsolationDatesFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/ContactDateCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/AddressForm/AddressForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/commentDisplay/commentDisplayStyles.ts
- client/src/components/App/Content/SignUp/SignUpForm/SignUpForm.tsx
- client/src/components/App/Content/UsersManagement/UsersFilter/UsersFilter.tsx
- client/src/components/App/Content/UsersManagement/UsersFilter/UsersFilterStyles.ts
- allow multiple selection on autocompletes without closing
- changed comment's font size on table
- changed the user management's filter component's size 
- removed unused imports
> Fix(ui bugs and imports): fixed ui bugs and removed unused imports

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
הגעתי למסקנה שזו בעיה של אסכרוניות של טעינת האובייקטים מהשרת, לכן השמשתי בUseEffect 
להשמת ה roleUbj
> fix(PersonalInfoTab):Bug #746, the dissapearing role

- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
[776](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/776)
> fix(useUsersManagement): fetch users according to the userType from the db

- server/src/DBService/Users/Query.ts
Change users query to fetch the correct investigations count.
> fix(user) change user's investigation count to be by creator

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
שלום לכולם,
לבהד 1 אני הולך,
את כל יתר הפרטים ממכם אני חוסך.
זהו השינוי האחרון שלי באבן יסוד,
אבל אני סומך עליכם שאתם תעשו עוד.
היה לי העונג לעבוד על הפרויקט איתכם,
ואני ממש אתגעגע אליכם.
תכלס לא נותרו בפי עוד מילים,
לכן רק אגיד שיהיה לכם **יום נעים!**
רדיו רדיו,
ויו יו,
נתראה בהמשך,
יניר
> fix(): fix db writing

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
> fix(): phonenumber - send null instead of empty srting

- server/src/DBService/Users/Mutation.ts
[747](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/747/)
> feat(reset-deskId) - changing investigation county will nullify deskId

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/Desk.ts
- server/src/ClientToDBAPI/DesksRoute/mainRoute.ts
- server/src/DBService/Desk/Query.ts
- server/src/Models/Desk/GetAllDesks.ts
[760](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/760/)
> feat(desk): display desks by county in investigations table

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- server/src/ClientToDBAPI/LandingPageRoute/mainRoute.ts
- server/src/DBService/LandingPage/Mutation.ts
[438](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/438/)
> feat(change-investigation-desk) - Changing desk in investigation table

- client/src/Utils/vendor/useContactFields.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCard.tsx
- disable delete on interaction that has a completed contact
> fix(interactions)

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/useInteractionsForm.ts
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- server/src/ClientToDBAPI/ContactedPeople/mainRoute.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- server/src/DBService/ContactedPeople/Mutation.ts
Can't save contacted people with the same identification number/identification number that already exists in the investigation
> feat(id-validations):

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
[833](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/833/)
> fix(investigationTable): add title for desk that were not assigned to investigation

- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/useTabManagement.ts
[812](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/812/)
> fix(useTabManagement): fix validation work properly

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/useInteractionsForm.ts
- server/src/ClientToDBAPI/ContactedPeople/mainRoute.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- server/src/DBService/ContactedPeople/Mutation.ts
-Added the validation on contact status change
-Handled some more errors
> fix(id-validations):

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/useInteractionsForm.ts
- db scripts/check_duplicates_ids.sql
- server/src/ClientToDBAPI/ContactedPeople/mainRoute.ts
- server/src/DBService/ContactedPeople/Mutation.ts
-Now you can't move a contact to complete without checking that id has no duplicates
> fix(duplicate id validations):

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/useInteractionsForm.ts
- db scripts/check_duplicates_ids.sql
- db scripts/update_contact_person.sql
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
made some changes to fix the bug in the mabar environment
> fix(duplicate ids error handling):

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
-handled the duplicate ids response
> fix(end investigation id validations):

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
-handle save contact duplicates error message
> fix(save contact validations):

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
-moved the check to the client
> fix(id validations in contact status):

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- set status to be active on first tab switch on a "new" investigation
> fix(investigation status)

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> fix(id validations on status change):

- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementTableHeaders.ts
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- client/src/models/enums/SignUpFields.ts
- add user name as secondary display name in user management
> fix (userManagement)

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- added type convertion that broke build
> fix(build)

- client/src/Utils/vendor/useContactFields.ts
- client/src/commons/CustomSwal/CustomSwalStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ExcelUploader/ContactUploader.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ExcelUploader/useContactExcel.ts
- client/src/models/enums/ContactType.ts
- client/src/models/enums/InteractedContact.ts
- client/src/models/enums/contactQuestioningExcelFields.ts
- added validations before starting a quarantine report
- now enables user to upload same file multiple times (if fixed etc...)
> Feat(contact questioning) quarantine validations

- client/src/components/App/App.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfoInterfaces.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/useInvestigatedPersonInfo.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/redux/Investigation/investigationActionCreators.ts
- client/src/redux/Investigation/investigationActionTypes.ts
- client/src/redux/Investigation/investigationReducer.ts
investigation status doesn't change when admin opens an investigation
> feat(admin status):

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGrid.tsx
[855](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/855/)
> feat(contact): disable if investigation was reopened

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
Moved most of the validations to the client and fixed some bugs regarding to
empty ids and validations on change tab
> fix(id-validation on ContactQuestioning):

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfoInterfaces.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/useInvestigatedPersonInfo.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- update investigation to be active on enter (table click)
> Fix(investigation status) update on investigation enter

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.test.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfoInterfaces.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfoStyles.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/useInvestigatedPersonInfo.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/InvestigationStatus.ts
- client/src/redux/Investigation/investigationReducer.ts
- client/src/redux/Status/statusesActionCreators.ts
- client/src/redux/Status/statusesActionTypes.ts
- client/src/redux/Status/statusesReducer.ts
- client/src/redux/rootReducers.ts
- client/src/redux/storeStateType.ts
- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- server/src/DBService/InvestigationInfo/Mutation.ts
- server/src/DBService/InvestigationInfo/Query.ts
[594](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/594/) 
[889](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/889/)
> Feat(sub status status reason)

- client/src/Utils/StatusUtils/useStatusUtils.ts
- client/src/Utils/vendor/useContactFields.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ExcelUploader/ContactUploader.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/NewInteractionEventDialog.tsx
- client/src/models/Contact.ts
- client/src/models/Contexts/InteractionEventDialogData.ts
- client/src/models/InteractedContact.ts
- db scripts/update_contact_event_function.sql
- db scripts/update_contact_person.sql
- db scripts/update_contact_persons.sql
- server/src/ClientToDBAPI/ContactedPeople/mainRoute.ts
- server/src/DBService/ContactEvent/Query.ts
- server/src/DBService/ContactedPeople/Query.ts
- server/src/Models/ContactEvent/GetContactEvent.ts
- server/src/Models/ContactedPerson/ContactedPerson.ts
- Now the validations of completed investigations is only on contacts and events created after the investigation was first ended.
- Now when saving on contact questioning there it is checked if all the contacts isolations are valid - if not, the invalid contact isnt saved.
> fix(contacts validations): fixed disabling contacts after completed conditinally and added isolation validations

- server/src/ClientToDBAPI/ClinicalDetailsRoute/mainRoute.ts
add else to avoid sending response twice for the same request
> fix(headers-erros): bug 956

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumn.tsx
[913](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/913)
> fix(InvestigationStatusColumn): icon shouldn't display If no reason was written

- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/useTabManagement.ts
solve bug 958
move lastTabDisplaiedId useEffect to investigation form.
> fix(finish-without-contacts): bug fix from test branch

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
[968](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/968/)
> fix(filter by desk) - closes when clicking the icon button and not only the close icon

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
[929](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/929/)
> fix(personalInfoTab): display error message in defense forces

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
[952](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/952/)
> fix(InteractionEventForm): cancel displaying error when placeType and placeSubType are correct

- client/src/components/App/Content/InvestigationForm/InvestigationFormInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/useTabManagement.ts
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
* add onCancel parmater to handleFinishInvestigation function
fix bug 960
> fix(cancel-finish-investigation)

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.test.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfoStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
[950](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/950/)
[954](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/954/)
[970](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/970/)
[971](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/971/)
> Fix(status select) - Change status and substatus autocomplete to select

- client/src/commons/Toggle/Toggle.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/NewInteractionEventDialog.tsx
- client/src/models/Contexts/InteractionEventDialogData.ts
-Toggle is now empty by default and not false
> fix(toggle default value):

- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementTableHeaders.ts
> fix(usersManagement): present and sort by username instead of fullName

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
[976](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/976/)
> fix(toggle): change if value is not null

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventSchema.ts
added a validation that makes sure that the client entered an end time
> fix(end time validation in contact event):

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
[986](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/986/)
> fix(externalization-toggle)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
[980](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/980/)
> fix(extetnalization approval): add error indication if extetnalization approval was not selected

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/commentDisplay/commentDisplay.tsx
- made comment tooltip disappear on scroll
> fix(investigation table) 

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventSchema.ts
[985](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/985/)
[977](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/977/)
> fix(interactionForm): create interaction even if externalization approval was not selected

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
> fix(contact event name):

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
> fix(reverse dates after event creation):

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/models/ResortData.ts
*change axios call order while loading exposures and flights data
> fix(resort-load): solve bug 984 resorts weren't loaded correctly

- client/src/Utils/auxiliaryFunctions/auxiliaryFunctions.ts
id sum needs to be greater than 0
> fix(id-validation):

- client/src/Utils/auxiliaryFunctions/auxiliaryFunctions.ts
id sum needs to be greater than 0
> fix(id-validation): (#802)

- client/src/index.css
- fixed scrolling prevention on dialog open
> fix(styles)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventSchema.ts
[1014](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1014/)
> fix(interactionSchema): undisabling externalization input when placeType is transportation and make it required

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
[1015](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1015/)
> fix(status-select)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetailsInterfaces.ts
This PR continues the axios change of setting is loading manually instead of on every axios request.
> feat(clinical-details) loader shows when fetching and saving form data

- client/src/commons/FormInput/FormInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/NewInteractionEventDialog/NewInteractionEventDialog.tsx
Set initial time  to empty instead of 00:00 and assure validation works fine
> fix(InteractionEventForm): set initial time  to empty instead of 00:00

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetailsInterfaces.ts
[992](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/992/)
> fix(isolationAddress): fix isolation address

- client/src/Utils/auxiliaryFunctions/auxiliaryFunctions.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
> fix(id and time validations in contact event creation):

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/useInvestigationTableFooter.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- server/src/DBService/LandingPage/Mutation.ts
- server/src/DBService/Users/Mutation.ts
between counties ONLY (US #1017)
> Feat(TransferInvestigation): make transfer indication when transfer

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/FamilyContactsDialog/FamilyContactsDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/FamilyContactsDialog/FamilyContactsDialogStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/FamilyContactsDialog/FamilyContactsTable/FamilyContactsTable.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/FamilyContactsDialog/FamilyContactsTable/FamilyContactsTableHeaders.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/FamilyContactsDialog/FamilyContactsTable/FamilyContactsTableStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTabInterfaces.ts
- client/src/models/InteractionsTabSettings.ts
- client/src/models/InteractionsTabUx.ts
- client/src/models/InvolvedContact.ts
- client/src/models/enums/InvolvementReason.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- server/src/DBService/ContactEvent/Query.ts
- server/src/DBService/InvestigationInfo/Mutation.ts
- server/src/DBService/InvestigationInfo/Query.ts
- server/src/Models/ContactEvent/GetContactEvent.ts
- server/src/Models/ContactEvent/GetInvolvedContacts.ts
[us](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/sprint%2012?workitem=1001).
In addition queried all the involved contacts and grouped them by involvement reason
> feat(family members): warning dialog when  there are not allowed uncontacted family members

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationNumberColumn/InvestigationNumberColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationNumberColumn/InvestigationStatusNumberStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumnStyles.ts
- client/src/styles/theme.ts
[1060](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1060/)
> fix(investigation-table-text-align) - Center table cells text + margin columns that may not have icons

- client/src/components/App/Content/LandingPage/InvestigationTable/FilterCreators.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- client/src/models/enums/InvestigationsFilterByFields.ts
- server/src/ClientToDBAPI/LandingPageRoute/mainRoute.ts
- server/src/DBService/LandingPage/Query.ts
* adding pagination to the investigation table
* when filtering or sorting the table it will go to the first page
* when sorting the users table it will go to the first page
> feat(InvestigationTable.tsx): add pagination to the table

- client/src/components/App/AppToolbar/AppToolbarStyles.ts
[1062](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1062)
> feat(decorate-active-toolbar) - decorate active toolbar item

- client/src/index.tsx
- client/src/styles/scrollbar.css
[1063](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1063)
> feat(scrollbar) - add scrollbar styles

- db scripts/update_contact_persons.sql
After contacted person is completed, a timestamp is added.
> feat(completionTime): adding completion time

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields/SymptomsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
-Changed post request to delete request
-Delete happens on date change too
> fix(delete irrelevant contact events):

- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
* check that that there is main status before asking substatus
> fix(substatus-404-error)

- client/src/Utils/vendor/useInvolvedContact.ts
- client/src/commons/Icons/FamilyContactIcon.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/FamilyContactsDialog/FamilyContactsTable/FamilyContactsTable.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
- client/src/models/Contact.ts
- client/src/models/InteractedContact.ts
- client/src/models/InvolvedContact.ts
- client/src/models/enums/contactQuestioningExcelFields.ts
- db scripts/update_contact_persons.sql
- server/src/ClientToDBAPI/ContactedPeople/mainRoute.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/DBService/ContactEvent/Query.ts
- server/src/DBService/ContactedPeople/Query.ts
- server/src/Models/ContactEvent/GetContactEvent.ts
- server/src/Models/ContactedPerson/ContactedPerson.ts
[1000](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/sprint%2012?workitem=1000)
> feat(involved contacts): added an indentification for family and involved contacts

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields/SymptomsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields/useSymptomsFields.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetailsInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
-Now warning message appears only on clinical details save
-Handled the case when getInvestigatedDates returns undefined
> fix(Irrelevant contact events deletion):

- client/src/commons/Icons/EducationContactIcon.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGrid.tsx
- client/src/models/InvolvedContact.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/DBService/ContactEvent/Query.ts
- server/src/Models/ContactEvent/GetInvolvedContacts.ts
[1057](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1057)
> feat(education display): indication education contacts and showing all relevant fields

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/InvestigationTableRow.ts
- server/src/ClientToDBAPI/GroupedInvestigationsRoute/mainRoute.ts
- server/src/DBService/GroupedInvestigations/Query.ts
- server/src/DBService/LandingPage/Query.ts
This PR adds the UI for grouped investigation on investigations table
> Feat(grouped investigations on investigations table)

- client/src/Utils/DateUtils/useDateUtils.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.test.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
> fix(get dates to investigate error handling):

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/InvestigationTableRow.ts
- server/src/ClientToDBAPI/GroupedInvestigationsRoute/mainRoute.ts
- server/src/ClientToDBAPI/GroupedInvestigationsRoute/utils.ts
- server/src/ClientToDBAPI/LandingPageRoute/utils.ts
- server/src/DBService/GroupedInvestigations/Query.ts
- server/src/DBService/LandingPage/Query.ts
This PR fixes some minor bugs on investigation table:
* add county to the fetched grouped Investigations
* add tooltip for the fetch and hide icons 
* fetchInvestigations and fetchGroupedInvestigations  will now also fetch group reason
> fix(group-reason) 

- .github/dependabot.yml
Take 2- the yml was invalid last time
> fix() fix invalid dependabot.yml

- client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/FilterCreators.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/enums/InvestigationsFilterByFields.ts
-Added a searchBar to the investigations table page
-Users can now search for investigations by epidemiology number/phone number/id number/full name
> feat(investigations searchBar):

- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
> fix(): changed the parameter name according to the mutation

- db scripts/update_contact_person.sql
> feat(update_contact_person): added functionality to add family member contact

- client/package-lock.json
- client/package.json
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/useInvestigatedPersonInfo.ts
> fix(error message when saving personal details):

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
> fix(search bar clear):

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsStyles.ts
> fix(ClinicalDetails):fix form margin

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioning.tsx
- server/src/DBService/ContactedPeople/Query.ts
- Adding sort by family contacts
- Sorting on the query and not on the client
> fix(contacts sort): sorting the contacts

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/GroupedInvestigations.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/useInvestigationTableFooter.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
* add reason tooltip
* move fetchTableData out of GroupedInvestigations - call it inside onDialogClose
> feat(investigationTable): add reason tooltip

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
[1125](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1125/)
> fix(InvestigationTableUnderline): add underline only to grouped investigations

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
> fix(): add ? to nullable parameters

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfoInterfaces.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/useInvestigatedPersonInfo.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
fix bug #1124 . now admin user can change investigation to 'New' status.
> fix(InvestigatedPersonInfo): 

- client/src/components/App/Content/LandingPage/InvestigationTable/FilterCreators.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/GroupedInvestigations.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/models/enums/InvestigationsFilterByFields.ts
[1126](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1126/)
[1140](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1140/)
> Fix(investigations search bar)

- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
[1154](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1154/)
> fix(userManagement-pagination) : set rowsPerPage to 100

- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/Users/Mutation.ts
This PR changes was investigation transferred to true when changing county of investigation groups ([this bug](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1155/)).
> fix() change was investigation transferred for groups

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/GroupedInvestigations.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/GroupedInvestigationsTable/GroupedInvestigationsTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/useInvestigationTableFooter.ts
[1156](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1156/)
> fix(groupedInvestigations): display all grouped investigations in table

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsTabs.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ManualContactsForm/ContactForm/ContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ManualContactsForm/ContactForm/ContactFormStyles.ts
- client/src/styles/formStyles.ts
inputs wont override each other and will spread to full length (same goes for family contact table)
[1161](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1161/)
> fix(contact-form-style)

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationNumberColumn/InvestigationNumberColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
[1165](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1165/)
> fix() : tooltips will be placed on top with an arrow

- client/src/Utils/FamilyContactsUtils/useFamilyContactsUtils.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ContactGrid/ContactGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionDetailsForm.tsx
- client/src/models/Contact.ts
- client/src/models/InvolvedContact.ts
- db scripts/update_contact_person.sql
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/DBService/ContactEvent/Query.ts
- server/src/Models/ContactEvent/GetInvolvedContacts.ts
[1159](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1159/)
> fix: now the family relationship is saved on family members

- client/src/components/App/Content/LandingPage/InvestigationTable/FilterCreators.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/models/enums/InvestigationsFilterByFields.ts
[1164](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1164/)
(also fixes investigations table status tooltip)
> fix search bar

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
[1175](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1175/)
> fix(isolation sources): now the other option is last

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/AirportInput/AirportInputStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsTabsStyles.ts
> fix(UI): ui fixes

- client/src/components/App/Content/LandingPage/InvestigationTable/FilterCreators.ts
[1180](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1180/)
> fix(searchBar-includes) - primaryPhone identityNumber and fullName search by includes

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
> fix(InvestigationTable): counter fixed

- client/src/commons/DatePick/DatePick.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
1. Change default error messages to be clear and red
2. Changed exposure date max date to be validation date
> fix(exposure date): changed ui and max date

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/SettingsActions/SettingsActions.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/SettingsActions/useSettingsActions.ts
[1189](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1189/)
> fix(): disband group on exclude action when two investigations were left

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- made history state map of ids instead of full values
- removed filterRules state and kept it in history
> fix(table filtering) - get current filter from history

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
[1188](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1188/)
> feat(popover-groupWithOneInvestigation):open a popover when group contains only one element on arrow click

- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- server/src/DBService/InvestigationInfo/Mutation.ts
US 1194 - 
When investigation is finished, close all unclosed isolated contacts.
> Feat(close isloated contact): On investigation finish close all isolated contacts  

- client/src/Utils/DateUtils/useDateUtils.ts
- client/src/components/App/Content/InvestigationForm/InvestigationForm.test.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.test.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
* change alert message while finish investigation
* change investigation days with unknown sympthoms from 10 to 7
> feat(finish-investigation-message)

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/SettingsActions/SettingsActions.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/SettingsActions/useSettingsActions.ts
-relocation it to be in the action settings component instead of column's cell.
> feat(reopen button): moving reopen investigation button

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/InvestigationTableRow.ts
- server/src/ClientToDBAPI/LandingPageRoute/utils.ts
- server/src/DBService/LandingPage/Query.ts
For  user stories:
1. 1158 - add SubOccupation (מוסד) column
2. 1128 - remove Priority column
3. 1149 - remove County column
> Feat(InvestigationTable): Modify columns

- client/src/commons/IsActiveToggle/IsActiveToggle.tsx
- client/src/components/App/AppToolbar/AppToolbar.tsx
- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
* add route for changing activity status by user id for admins.
* change isActiveToggle prop name from setUserActivityStatus to onToggle.
* make the activity status toggle in the users table work.
> feat(update-is-user-active)

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoValidationSchema.ts
We would like to restrict the user from typing class number that is greater from 50
> feat(Class number Validation): class number value max is 50

- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementStyles.ts
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/Users/Mutation.ts
Add option to change user source organization on users management table
[1216](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1216/)
> feat(change-user-source-organization)

- client/src/commons/AlphabetWithDashTextField/AlphabetWithDashTextField.tsx
- client/src/commons/AlphabetWithDashTextField/AlphabetWithDashTextFieldTypes.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ManualContactsForm/ContactForm/ContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/BusinessContactForm/BusinessContactForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventForm.tsx
This pr changes the validations on interactions form, contact first and last name can now contain '-' ,also in order to external an interaction both place name and description should be filled
[1151](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1151/)
> feat(Alphabet-With-Dash-Text-Field): Create alphabet text field that accepts '-'

- server/src/DBService/LandingPage/Query.ts
- add relevant field to non-admin query
> fix(date tooltip)

- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagementStyles.ts
link to Bug:[1195](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1195/)
> Fix(display-all-rows-interactions-tab): Changed Styles to see all items in InteractionsTab when there is error in Tabs

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationTabs.tsx
- client/src/styles/theme.ts
[1113](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1113/)
> Feat (change font)

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
[1190](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1190/)
> fix(personal-info-role): Occupation change will reset roleObj

- client/src/components/App/Content/LandingPage/InvestigationTable/SettingsActions/SettingsActions.tsx
[1248](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1248/)
> Fix(settings-actions-disabled-action): A click on a settings action would not trigger investigation open

- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementStyles.ts
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/Users/Mutation.ts
- server/src/DBService/Users/Query.ts
[1214](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1214/)
> feat(usersManagement): add option for admins to update user desk

- client/src/Utils/ContactEvent/placeTypesCodesHierarchy.ts
- client/src/Utils/ContactEvent/useContactEvent.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/AddressGrid/AddressGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/MedicalLocationGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/OtherPublicLocationGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/TransportationAdditionalGrids/TransportationEventGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventSchema.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/PatientAddress.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/SchoolEventForm/SchoolEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/useInteractionsForm.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/models/DBAddress.ts
[1213](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1213)
> feat(patient address): changed the address to be patient's on subPlace is his house

- client/src/components/App/AppToolbar/AppToolbar.tsx
https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1237
> feat(connected to county): Changed from office to county

- client/src/components/App/Content/SignUp/SignUpForm/SignUpForm.tsx
[1251](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1251)
> fix(): display deskName on the user info dialog 

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationCounty.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationDesk.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationTabs.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationTabsDialog.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorAllocationDialog.tsx
[1254](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1254/)
> fix(transfer-investigations-success): Add success alert when investigation transfer is successful

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorAllocationDialog.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
Link to Bug: [1250](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1250/)
> Fix(update-investigators-list): Added fetch call every time allocating investigator to get updated list according to active/unactive state of Admin

- client/src/commons/AlphabetTextField/HebrewTextField.tsx
- client/src/commons/HebrewTextField/HebrewTextField.tsx
- client/src/commons/HebrewTextField/HebrewTextFieldTypes.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
Adding a Hebrew text field and changing the relationship field to Hebrew text field.
[Bug: 1256](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1256/)
> Adding a Hebrew text field

- .github/dependabot.yml
This PR changes the time interval which Dependabot will search for new versions of dependencies.
> feat() change dependabot interval from daily to weekly

- client/src/components/App/Content/LandingPage/InvestigationTable/DeskFilter/DeskFilter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/DeskFilter/DeskFilterStyles.ts
This PR changes the styling of desk filter to make it a bit smaller.
> fix() reduce desk filter padding and tag limit

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/usePersonalInfoTab.ts
- client/src/models/DBAddress.ts
- server/src/ClientToDBAPI/ClinicalDetailsRoute/mainRoute.ts
- server/src/ClientToDBAPI/PersonalDetailsRoute/mainRoute.ts
- server/src/DBService/Address/Mutation.ts
- server/src/DBService/ClinicalDetails/Query.ts
- server/src/DBService/PersonalDetails/Query.ts
- server/src/Models/Exposure/CovidPatientDBOutput.ts
Link to Bug: [1258](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1258/)
> Fix(update-investigation-address): When addressId exists now updates instead of creating new

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- server/src/ClientToDBAPI/Address/mainRoute.ts
- server/src/ClientToDBAPI/ClinicalDetailsRoute/mainRoute.ts
- server/src/ClientToDBAPI/ContactedPeople/mainRoute.ts
- server/src/ClientToDBAPI/CountiesRoute/mainRoute.ts
- server/src/ClientToDBAPI/DesksRoute/mainRoute.ts
- server/src/ClientToDBAPI/EducationRoute/mainRoute.ts
- server/src/ClientToDBAPI/ExposureRoute/mainRoute.ts
- server/src/ClientToDBAPI/GroupedInvestigationsRoute/mainRoute.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
- server/src/ClientToDBAPI/LandingPageRoute/mainRoute.ts
- server/src/ClientToDBAPI/PersonalDetailsRoute/mainRoute.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/ClinicalDetails/Mutation.ts
- server/src/DBService/ClinicalDetails/Query.ts
- server/src/DBService/Counties/Query.ts
- server/src/DBService/Desk/Query.ts
- server/src/GraphqlHTTPRequest.ts
- server/src/Logger/Logger.ts
- server/src/Models/Address/Address.ts
- server/src/Models/ClinicalDetails/GetInvestigatedPatientClinicalDetailsFields.ts
- server/src/Utils/InvestigationComplexity/InvestigationComplexity.ts
- server/src/Utils/addressUtils.ts
- server/src/Utils/patientUtils.ts
- server/src/middlewares/Authentication.ts
- server/src/middlewares/HandleInvestigationRequest.ts
1. dealing sb errors globaly: graphql request was sending queries and mutations errors inside the reault's body. Now, those errors are throwing an exception on the graphqlRequest function.
2. logs structre: I have noticed there is an inconsistent logging on the server - some of the routes doesnt have logs at all, and most of the ones that have dont have an consistent structre. So, I wrote a common version to use for each status - launching reuques, successful response and error.
3. minor changes - "cleaning the code": moved common functions to utils and changed names and return values to be better
> fix(server): server logs, errors and small fixtures

- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
when no place SubType  selected Bug #1264
> Fix(PlacesTypesAndSubTypes): post default placeSubType  

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
changed the logs of all the transfering investigations functions and of the onInvestigationRowClick function to be more informative
> fix(investigations logs): changed logs to be more informative

- client/src/Utils/auxiliaryFunctions/auxiliaryFunctions.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactSection/Schemas/contactQuestioningPersonal.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoValidationSchema.ts
- client/src/components/App/Content/SignUp/SignUpForm/SignUpSchema.ts
[1276](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1276/)
[1278](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1278/)
>  fix(contact-questioning): fixed bugs of contact questioning tab

- client/package-lock.json
- client/src/components/App/Content/LandingPage/adminLandingPage/investigationsInfo/InvestigationBarChart/InvestigationBarChart.tsx
the tooltip for inactive investigators has been cut by the card
change the tooltip position to absolute
> fix(InvestigationBarChart.tsx): fix the tooltip location

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventForm.tsx
- fix form reset after selecting patient's house sub category
> fix(contact event) form reset

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/SelfInvestigationIcon/SelfInvestigationIcon.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/SelfInvestigationIcon/Tooltip/SelfInvestigationTooltip.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/SelfInvestigationIcon/selfInvestigationIconStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/SelfInvestigationIcon/useSelfInvestigationIcon.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/InvestigationTableRow.ts
- client/src/models/enums/selfInvestigationStatuses.ts
- server/src/DBService/GroupedInvestigations/Query.ts
- server/src/DBService/LandingPage/Query.ts
added new reference to whether the investigation was created from an investigation form
fixes [1325 ](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1325/) [1324 ](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1324/)  [1323 ](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1323/) [1322](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1322/)
> Feat/new self-investigation icons

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorAllocationDialog.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorsTable/InvestigatorsTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorsTable/InvestigatorsTableHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- db scripts/get_investigator_list_by_county_function.sql
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/Users/Query.ts
Fixing bug [1305](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1305)
Due to performance issue in Prod environment. I change investigator fetch - now fetching by sql query called from function (instead of graphQL query). Thus, I was forced to fit  some client parsing to the returning object
> fix(InvestigatorsTable): refactor investigator list fetch

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
> aligned healine

- client/src/components/App/Content/LandingPage/InvestigationTable/DeskFilter/DeskFilter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/DeskFilter/DeskFilterStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/TableFilter/TableFilter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/TableFilter/TableFilterStyles.ts
Fix to Bug: [1274](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1274/)
> Fix(UI-filter-box): Changed styles

- client/src/components/App/Content/LandingPage/InvestigationTable/SelfInvestigationIcon/Tooltip/SelfInvestigationTooltip.tsx
changed date format to european format + added time
> changed to date-fn's format

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooterInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationInvestigator.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/useInvestigationTableFooter.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/InvestigatorOption.ts
- client/src/models/User.ts
- db scripts/get_investigator_list_by_county_function.sql
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/Users/Query.ts
Due to perfomance issue I changed fetching investigator's fetch to be by SQL Function.
Now,  a json object of user returned from DB.
**Since DB user object is different from  User interface I had to add my own Inteface  (FetchedUser).**
this might be  tested  with DB  CoronaiTest1  which is copy of Test DB
> fix(Investigators): Change  investogator fetch  for Test env

- client/src/components/App/AppToolbar/useAppToolbar.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/AdminLandingPageFilters.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/TimeRangeFilterCard.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/useTimeRangeFilterCard.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/adminLandingPage.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/desksFilterCard/desksFilterCard.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/desksFilterCard/useDesksFilterCard.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/useAdminLandingPage.ts
- server/src/ClientToDBAPI/LandingPageRoute/mainRoute.ts
The fixtures are:
1. When entering invalid date there isnt a crush.
2. The state is saved on refresh on the history.
3. The filters are applied only when clicking the update button
> fix(admin landing page): bug fixtures

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorAllocationDialog.tsx
[1347](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1347/), [1348](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1348/), [1350](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1350/)
> fix(display bugs): fixed style ans texts

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo/ReachContact.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
[1344](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1344/), [1343](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1343/), [1352](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1352/)
> fix(questioning and table): fixed bugs

- client/src/components/App/Content/LandingPage/InvestigationTable/DeskFilter/DeskFilter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/DeskFilter/DeskFilterStyles.ts
fixes [1274](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1274)
> changed desks filter size

- client/src/Utils/Contacts/ContactIdValidationSchema.ts
- client/src/Utils/auxiliaryFunctions/auxiliaryFunctions.ts
Now typing in hebrew characters in passport field shows an error same as id field
> fix(Hebrew characters in passport field):

- client/src/commons/Forms/PlacesTypesAndSubTypes/usePlacesTypesAndSubTypes.ts
change current function 'moveOtherValueLocationToLast' to a placeSubTypes sort function, with other value at last.
[bug 1336](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1336/)
> sort place sub types, and move other to last

- client/src/Utils/auxiliaryFunctions/auxiliaryFunctions.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
1. investigation table fetch is commited once on page load
2. allowing id to be only numbers
> fix(investigation table + id)

- client/src/Utils/Contacts/ContactIdValidationSchema.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
remove the basic id validation from the passport schema to allow letters and "/"
> fix(passport schema validation):

- client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/TimeRangeFilterCard.tsx
Fix to bug:[1366](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1366/)
> Fix(filter-by-time-range-card-label-naming)

- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
- client/src/commons/Forms/PlacesTypesAndSubTypes/usePlacesTypesAndSubTypes.ts
- client/src/commons/Forms/PlacesTypesAndSubTypes/usePlacesTypesAndSubTypesInterfaces.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventForm.tsx
- client/src/redux/PlaceTypes/placetypeActionCreators.ts
- client/src/redux/PlaceTypes/placetypeActionTypes.ts
- client/src/redux/PlaceTypes/placetypeReducer.ts
- client/src/redux/rootReducers.ts
- client/src/redux/storeStateType.ts
- small refactor to place type select to solve bugs [#1314](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1314), [#1338](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1338), [#1339](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1339), [#1341](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1341)
- fixed sync between place type and sbubtype selection
- exported subplaces to redux to prevent refetching
> fix(place type form) refactor 

- client/src/components/App/Content/LandingPage/InvestigationTable/DeskFilter/DeskFilterStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
[1274](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1274)
> Fix(DeskFilter): redesign by bug 1274

- client/src/Utils/Contacts/ContactIdValidationSchema.ts
- client/src/Utils/Schemas/identification.ts
- client/src/Utils/auxiliaryFunctions/auxiliaryFunctions.ts
User can now type in passport by this condition: An alphanumeric string with 10 characters or A numeric string and a possible "/".
> fix(passport validations):

- server/src/DBService/ClinicalDetails/Query.ts
Fix to bug: [1383](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1383/)
> Fix(isolation-sources-order)

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/SettingsActions/SettingsActions.tsx
- server/src/DBService/LandingPage/Query.ts
1. showing the settings col for not admins as well
2. hiding the exclude button when not admin
> Fix(settings col)

- client/src/Utils/ClinicalDetails/symptomsUtils.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
Fix to bug: [1384](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1384/)
> fix(isolation-dates-validation)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/useInteractionsForm.ts
the problem is that sometimes the client sends duplicated requests to the server at POST : '/intersections/createContactEvent'
(on useInteractionsForm)
the client appears to send 2 requests but the log shows only 1 response, so we've figured that maybe it's the if that's preventing us from seeing the 2nd response so we're adding a debugging log to it
> added debugging log on axios's else

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoValidationSchema.ts
Fix to Bug: [1388](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1388/)
> Fix(education-class-number-validation)

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Schema/flightsValidation.ts
Fix to bug: [1394](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1394/)
> Fix(end-flight-date-validation)

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Schema/flightsValidation.ts
Fix to bug: [1396](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1396/)
> fix(flight-date-error-naming)

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureSearchTextField/ExposureSearchTextField.tsx
fixes [1398](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1398)
+removed unnecessary placeholder
> added 'epidemiology number' to placeholder text

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
Fix to bug:[1397](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1397/)
> Fix(institution-field-styles)

- client/src/commons/Select/SelectDropdown.tsx
- client/src/components/App/AppToolbar/AppToolbar.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/CommentDialog/CommentDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/BackgroundDiseasesFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo/ReachContact.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/PlacesAdditionalGrids/DefaultPlaceEventGrid.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/TransportationForms/BusEventForm.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationIndicatorsColumn/InvestigationIndicatorsColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationTabs.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/desksFilterCard/desksFilterCard.tsx
- client/src/components/App/Content/SignUp/SignUp.tsx
- client/src/components/App/Content/UsersManagement/UserInfoDialog/UserInfoDialog.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementStyles.ts
- client/src/models/FilterTableOption.ts
- client/src/models/InteractedContact.ts
- client/src/models/InvestigationInfo.ts
removed unused imports
fixed spacing
used single quotes
fixed imports order
> fix(): removed unused imports, fixed spacing and used single quotes

- client/src/Utils/Contacts/ContactIdValidationSchema.ts
- client/src/commons/AlphanumericTextField/AlphanumericTextFieldTypes.ts
- client/src/commons/Forms/AddressForm/AddressForm.tsx
- client/src/commons/Forms/AddressForm/AddressFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureSearchTextField/ExposureSearchTextFieldStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/TransportationForms/TrainEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTabStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationIndicatorsColumn/InvestigationIndicatorsColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableRow/InvestigationTableRow.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/investigationsInfo/investigationsInfo.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/investigationsInfo/investigationsInfoStyles.ts
* the form house details height and label positioning
* removing all unused vars in the client project
> fix(Addresses): fix house details height and label positioning

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/CommentDialog/CommentDialog.tsx
[#1410](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1410)
- fixed comment sync on update & delete
- doesnt reset after save
> fix(comment dialog)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/IsolationDatesFields.tsx
fixes [1416 ](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1416)
> removed helper text - clinicalDetails date picker

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTabStyles.ts
Fix to Bug:[1397](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1397/)
> Fix(institution-field-sizes)

- client/src/components/App/Content/UsersManagement/UsersFilter/UsersFilter.tsx
- server/src/DBService/Users/Query.ts
ordering from A-Z userType and active status
fixes [1415](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1415)
> ordered userManagementTable

- client/Dockerfile
- client/server/logger.js
- client/server/package-lock.json
- client/server/package.json
- client/server/server.js
- client/src/setupProxy.js
The user is getting weird 504 errors 
* Add informative logs to the reverse proxy
* Post those logs with network data to azure application insights
> feat(monitoring): add monitoring for the reverse proxy

- client/src/components/App/Content/UsersManagement/UsersFilter/GenericAutoComplete.tsx
- client/src/components/App/Content/UsersManagement/UsersFilter/UsersFilter.tsx
- client/src/components/App/Content/UsersManagement/UsersFilter/UsersFilterStyles.ts
- client/src/models/ActiveStatus.ts
> fix(UserFilter): created seperate component for genericAutoComplete and fixed style

- client/src/Utils/DateUtils/timeSince.ts
- client/src/commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/LastUpdateMessage/LastUpdateMessage.tsx
- client/src/models/enums/Times.ts
Fix to Bug: [1414](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1414/)
The problem was that when rendering the value wasn't fetched yes so the x-button won't appear so it was needes to add defaultValue so the X button will appear at all times.
> Fix(autoComplete-fields-x-button)

- client/src/components/App/Content/LandingPage/InvestigationTable/TableFilter/useTableFilter.ts
Fix to bug:[1426](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1426/)
> Fix(date-range-error-message)

- client/src/commons/AirportTextField/AirportTextFieldTypes.ts
- client/src/commons/InternationalCityTextField/InternationalCityTextFieldTypes.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/FlightsForm.tsx
Fix to bug:[1434](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1434/)
> fix(spacing-flights-form)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
Fix to bug:[1440](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1440/)
> fix(validation-symptoms-start-date)

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
Fix to bug: [1439](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1439/)
Added trigger that make rechecking of errors
> fix(error-message-identification-type)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventForm.tsx
- fixed externalization approval condition
- now only requires place description or name instead of both
> fix(contact event) externalization approvals

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTabStyles.ts
Fix to bug: [1442](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1442/)
Added styles to error label
> fix(error-message-class-number)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/usePersonalInfoTab.ts
- client/src/models/DBAddress.ts
- server/src/ClientToDBAPI/ClinicalDetailsRoute/mainRoute.ts
- server/src/ClientToDBAPI/PersonalDetailsRoute/mainRoute.ts
- server/src/DBService/Address/Mutation.ts
- server/src/DBService/ClinicalDetails/Query.ts
- server/src/DBService/PersonalDetails/Query.ts
- server/src/Models/Exposure/CovidPatientDBOutput.ts
Fix: removed update address functionality and return to always creating new address.
> fix(addresses-creation)

- client/src/commons/DatePick/TimePick.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventForm.tsx
fixes [1454](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1454/)
> added end time validation to interactions tab

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/AirportInput/AirportInputStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/FlightFormStyles.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/FlightsForm.tsx
Fix to bug: [1434](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1434/)
> fix(styles-flights-form)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/usePersonalInfoTab.ts
- client/src/models/DBAddress.ts
- server/src/ClientToDBAPI/ClinicalDetailsRoute/mainRoute.ts
- server/src/ClientToDBAPI/PersonalDetailsRoute/mainRoute.ts
- server/src/DBService/Address/Mutation.ts
- server/src/DBService/ClinicalDetails/Query.ts
- server/src/DBService/PersonalDetails/Query.ts
- server/src/Models/Exposure/CovidPatientDBOutput.ts
Fix: removed update address functionality and return to always creating new address.
> fix(removing-update-address)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
[1432](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1432)
> feat(change-interaction-chevron): Change chevron right to left

- client/src/Utils/UsersUtils/useUsersUtils.ts
- client/src/Utils/UsersUtils/userUtils.ts
- client/src/commons/SearchBar/SearchBar.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorsTable/InvestigatorsTable.tsx
- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
1. Added the userUtils files and exported there both default value and userValidationSchema.
2. Changed the search bar to get the validationSchema as props
3. Changed the user's validation to be as the dictionary and not alphanum as before
> fix(serach bar): changed the validations and added utils

- client/src/Utils/Contacts/useContactFields.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo/useReachContact.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactSection/Schemas/contactQuestioningPersonal.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ExcelUploader/ContactUploader.tsx
- client/src/models/enums/ContactStatus.ts
- client/src/models/enums/ContactStatusCodes.ts
This pr has fixtures for:
1. [1465](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1465/) - Whenver the status is absent, the status new is applied to the contact
2. When adding contact with tight type and not creating isolation, an error message will pop
> Fix(excel bugs)

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Schema/flightsValidation.ts
Fix to bug:[1474](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1474)
> Fix(flight-date-validation)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/useAccordionContent.ts
changed the refrence to count the correct id.
> fix/grouped investigation form-accordion row count

- client/src/Utils/Contacts/ContactIdValidationSchema.ts
- client/src/Utils/Schemas/identification.ts
- client/src/Utils/UsersUtils/userUtils.ts
- client/src/Utils/auxiliaryFunctions/auxiliaryFunctions.ts
- client/src/commons/AlphabetTextField/AlphabetTextField.tsx
- client/src/commons/AlphabetTextField/ExposureSearchTextField.tsx
- client/src/commons/AlphabetWithDashTextField/AlphabetWithDashTextField.tsx
- client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
- client/src/commons/FlightNumberTextField/FlightNumberTextField.tsx
- client/src/commons/HebrewTextField/HebrewTextField.tsx
- client/src/commons/NumericTextField/NumericTextField.tsx
- client/src/commons/Regex/Regex.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/CommentDialog/CommentInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactSection/Schemas/contactQuestioningClinical.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactSection/Schemas/contactQuestioningPersonal.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureSearchTextField/ExposureSearchTextField.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureSourceOption.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventSchema.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/TransportationForms/FlightEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTabValidationSchema.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/FilterCreators.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/GroupedInvestigationsForm/GroupedInvestigationsSchema.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationCountySchema.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationDeskSchema.ts
- client/src/components/App/Content/SignUp/SignUpForm/SignUpSchema.ts
- server/src/ClientToDBAPI/ExposureRoute/mainRoute.ts
- server/src/commons/Regex/Regex.ts
This PR implements: [1307](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1307/)
In CLIENT: create of regex file in commons with all the regex in the client files.
In SERVER: create of commons folder with regex files that contains all the regex in server files.
> Feat(regex-refactor)

- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- db scripts/close_isolate_contacts.sql
fixes US [1477](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1477/)
> Close valid contacts

- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/DBService/ContactEvent/Query.ts
changed connected status to always be new instead of same status
> changed connected contact status to new

- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementStyles.ts
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- db scripts/deactivate_all_county_users.sql
- db scripts/update_user_by_form.sql
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
- server/src/DBService/Users/Mutation.ts
This PR implements feature [1485](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1485)
In this PR I added deactivation button that appear only to users from type ADMIN and that when clicked updates all the users of the current county activity statuses to false.
Added new route for that purpose and new DB function.
> Feat(deactivate-all-county-users)

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/FlightsForm.tsx
Fix Bugs: [1450](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1450/) & [1493](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1493/)
> Fix(flight-dates-errors)

- client/src/Utils/ClinicalDetails/symptomsUtils.ts
> TEST - fix/changed calcultaion of dates to investigate

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
fixes [1472](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1472)
> added color to user cols

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/ContactsTable/tableColumns.ts
fixes [1498](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1498/)
> changed groupedInvestigationContact table column wording

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/useAccordionContent.ts
fixes [1497](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1497/)
> added phonenumber to search bar

- db scripts/deactivate_all_county_users.sql
fixes [1496](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1496/)
> removed 'admin.group' from deactivateAllCountyUsers

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
PR to user-story: [1494](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1494)
Text info changes due to us change
> feat(new-static-fields-text-changes)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/ContactDateCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/InteractionCard.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/RepetitiveEventIcon.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/RepetitiveEventIconStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialogStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/RepetitiveEventForm/hooks/useDateLoading.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
- client/src/models/Contexts/InteractionEventDialogData.ts
- server/src/DBService/ContactEvent/Query.ts
- added repetitive event indication
- added confirmation dialog before save
> feat|fix(repetitive events)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionFormTabSwitchButton.tsx
- only show warning dialog for repetitive events on repetitive events
- fixed validation when editing repetitive contact
- added ״is repetitive״ form field in disabled mode when editing
> fix(repetitive contact events)

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
Fix to bug: [1518](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1518)
> fix(load-address-automatically)

- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
Fixes Bug: [1533](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1533)
NOTE : this will need further look in next version, it's not the most perfect solution to the problem but it makes things back to work for now. 
More information detailed in the bug ticket.
> fix(transfer-grouped-investigations-county)

- server/src/DBService/ContactEvent/Query.ts
removed the field in the creation of a new contact
> removed contactedPersonCity from query

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
Fix to bug: [1536](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1536)
> fix(tool-tip-no-info-message-on-new-fields)

- client/src/commons/Regex/Regex.ts
fixes [1542](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1542/)
> added space in user search regex

- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
Fix to bug: [1541](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1541)
>  fix(add-fetch-investigations-by-group-id-on-county-transfer)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/TableFilter/useTableFilter.ts
Fix to bug: [1544](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1544)
> Fix(date-pick-validation-error-messages)

- db scripts/function_get_investigations_statistics.sql
- server/src/ClientToDBAPI/LandingPageRoute/mainRoute.ts
- server/src/DBService/LandingPage/Query.ts
moved wonky grqphql count into postgres function so that all of the statistics are calculated from a pre-filtered table instead of all investigations
> changed investigation statistics to function

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/ContactsForm.test.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/ContactsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/AccordionContent.test.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/SelectedRowsMessage/SelectedRowsMessage.tsx
fixes [1551](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1551/)
> changed phrasing of total rows

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorsTable/InvestigatorsTable.tsx
User story: [1561](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2015?workitem=1561)
> add to search

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableRow/InvestigationTableRow.tsx
fixes [1554](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2015?workitem=1554) 
hidden checkbox for regular investigators
> removed checkbox for investigaitors

- db scripts/function_get_investigations_statistics.sql
the problem of the slowness mainly came from the prev. implementation of unusualCompletedNoContactInvestigationsCount ,
which was O(n^2),  (run through all of the investigations for each of them, run througn all of the contacts), which was especially problematic with the size of those tables ( 40,000 investigations in 'ella' county * 1.3 mil (!) rows in contact persons ).
my solution offers O(2n) Complexity rate:
first we take all of the completed investigation's count. 
second we're joining contact person's table with contact event and with investigation to create this structure:
| epidemiology_number | event_id | person_id |
|:-------------------:|:--------:|:---------:|
note that I'm using inner join so as I would not get any empty fields (meaning an event with no contacts or an …
> redid no contacts query

- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementStyles.ts
- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
This PR implements feature: [1535](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1535)
Added counter of investigators to user management page.
> Feat(investigators-counter)

- .github/workflows/test_prs.yml
> adding wiki link for comment bot

- client/src/commons/Contexts/ContactBankContext.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankTable/ContactsBankTable.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankTable/Row/Row.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankTable/Row/useRow.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankTable/TableColumns.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankTable/TableHeader/TableHeader.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/contactsBankFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsTabs.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/Forms.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/ContactsTable/TableRows/useTableRows.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/useInteractionsForm.ts
- client/src/models/Contact.ts
- server/src/DBService/ContactEvent/Query.ts
Adds UI according to the user story, this does not include the functionality - that will be added after this PR thanks to #1356 
also changes provider context form grouped investigations
> 1563/feat/contact bank UI

- .github/labeler.yml
- db scripts/add_contacts_from_bank.sql
added new automatic label for DB changes
look at the actions below
> Db auto label

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankSearchBar/ContactsBankSearchBar.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankSearchBar/contactsBankSearchBarStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankTable/ContactsBankTable.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankTable/useContactsBankTable.ts
added a functional search bar to contacts bank
> contacts bank - added search bar

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/useInteractionsForm.ts
- server/src/ClientToDBAPI/IntersectionsRoute/mainRoute.ts
- server/src/DBService/ContactEvent/Mutation.ts
integrating #1357 and #1356
after this PR will be merged, TFS ticket 1532 can be started to work on.
> contact bank integration

- client/src/components/App/Content/UsersManagement/useUsersManagement.ts
- client/src/models/SignUpUser.ts
Fix to bug: [1587](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1587/)
>  1587/fix/remove-unassignedUser-from-investigators-count

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsBank/ContactsBankTable/Row/Row.tsx
added blank personal info and tight contact default values
> added default values to contacts bank

- client/src/TestHooks.tsx
fix history package error cause by the bot builds
> fix error from builds

- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
the problem was that the HandleCountyRequest import was uncapitalized
> added capital

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableRow/CommentCell/CommentCell.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableRow/CommentCell/commentCellStyles.ts
added 'hide comment' button to hide long comments
> added 'hide comment' button for long comments

- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/components/App/Content/UsersManagement/UsersFilter/FilterCreators.ts
- client/src/components/App/Content/UsersManagement/UsersManagement.tsx
- client/src/components/App/Content/UsersManagement/UsersManagementStyles.ts
- client/src/components/App/Content/UsersManagement/UsersManagementTableHeaders.ts
- client/src/models/Investigator.ts
- server/src/DBService/LandingPage/Query.ts
User Story: [1605](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1605/)
- Add authority column to users table.
- Add authority name to search bar in users management.
- Add authority name to investigator name in investigation table.
> Add authority to users table

- client/src/Utils/Contacts/useDuplicateContactId.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ExcelUploader/ContactUploader.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ContactsTabs.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/Forms.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ManualContactsForm/ContactForm/ContactForm.tsx
hiding contacts bank and re-adding duplicate contact ids
> Contact bank rollback

- server/src/DBService/Users/Mutation.ts
> removed 'last updator' from alloction query params

- client/src/Utils/Contacts/useContactFields.ts
> changed isolation id validation

- client/src/models/TrackingRecommendation/trackingOptions.ts
> fixed typo

- client/src/components/App/useApp.ts
> moved usersTypesFetch to only be called once

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationMetadata/InvestigationMetadata.tsx
if there was no update time - it'd return 1/1/1970
> added exception for no update time

- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagementStyles.ts
> moved next page button to tabs row

- server/.gitignore
since local servers (woo) i've added 2 more .env files - one for remote and one for local - just adding them to gitignore
> add-remote and local env to igonre

- client/src/components/App/Content/LandingPage/InvestigationTable/TableFilter/useTableFilter.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/TimeRangeFilterCard.test.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/useTimeRangeFilterCard.ts
- db scripts/function_get_investigations_statistics.sql
- server/src/DBService/LandingPage/Query.ts
added 00:00:00 to start date filter and  23:59:59 to end date filters so that the filter will be from the start of startdate to the end of enddate 🚀 
contains  a server script aswell
> added start and end of date time exceptions

- client/src/components/App/AppToolbar/useAppToolbar.tsx
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/components/App/useApp.ts
> changed logger setup to be more descriptive

- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
problem description in the tfs, added check to see if the investigation number is default and moved the request to another location
> moved setGroupedInvestigations to seperate file

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
after a conversation with Einat - changed the timer's speed and removed auto-close of the popup
> changed timer redirect speed

- client/src/Utils/DateUtils/formatDate.ts
- client/src/Utils/FamilyContactsUtils/FamilyContactsTableHeaders.ts
- client/src/Utils/FamilyContactsUtils/useFamilyContactsUtils.ts
adding new epidemiologic status fields to family contacts table 
Added an optional parameter called **noInfoText** which is what you type in case of empty or invalid date ( defaults to 'אין מידע' )
> added epidemiologic status to family contacts

- server/src/ScriptRunner/Scripts/index/BLK_person_contact_details.sql
damn, I didn't follow the [wiki page](https://github.com/CoronaTeamMOD/CoronaInvestigation/wiki/Writing-and-inserting-SQL-Scripts) **THAT I WROTE**
BTW READ IT PLZ
> added 'if exists' to column drop

- server/src/ScriptRunner/Scripts/index/update_contact_person.sql
> fixed wrong contact_person field refrence

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/useAccordionContent.ts
> change count refrence

- server/src/ClientToDBAPI/AuthorityRoute/mainRoute.ts
- server/src/ClientToDBAPI/CountiesRoute/mainRoute.ts
- server/src/ClientToDBAPI/DesksRoute/mainRoute.ts
- server/src/ClientToDBAPI/DistrictsRoute/mainRoute.ts
- server/src/ClientToDBAPI/EducationRoute/mainRoute.ts
- server/src/ClientToDBAPI/PersonalDetailsRoute/mainRoute.ts
- server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
> changed capitalization on UseCache

- server/src/ClientToDBAPI/Address/mainRoute.ts
> useCache :(

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
problem was that contact bank validation was present at edit of current event - added validation to see if contact is in current investgation
> added current investigation exception to current event ids

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
- client/src/models/Contact.ts
see bug for reference 
issue was that the server was still sending `ת"ז` instead of the ID number. 
also re-typing
> formatted family members pre submit

- server/src/ScriptRunner/Scripts/index/0_insert_new_desks.sql
- server/src/ScriptRunner/Scripts/index/1_insert_new_cities.sql
added new scripts for the new desks and cities
> insert desks and cities

- client/src/commons/NoContextElements/AddressForm.tsx
> added house num label

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/FamilyMembers/FamilyMembersForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/FamilyMembers/FamilyMembersTable/FamilyMembersTable.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/FamilyMembers/FamilyMembersTable/useFamilyMembersTable.ts
added a check to see if family member exists in bank and if so - disable its row
> added existing family member check

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionEventForm.tsx
- client/src/models/enums/InteractionsEventDialogContext/InteractionEventDialogFields.ts
> changed private house to apartment

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ManualContactsForm/ContactForm/ContactForm.tsx
default value was missing from controller
> added default value to controller

- server/src/ClientToDBAPI/ScriptsRoute/mainRoute.ts
removed middleware for testing in test-mabar
> removed developer request on scripts route

- client/src/commons/FormRowWithInput/FormRowWithInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTabStyles.ts
> re-aligned fields on personal info tabs

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/ManualContactsForm/ContactForm/ContactForm.tsx
Issue was that the validation for existing contact bank didn't take into account existing connected contacts from the current event.
added an exception to that
> added existing contact bank case

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureFormStyles.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/SearchCovidPatients/SearchByPersonalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/SearchCovidPatients/searchStyles.ts
> aligned exposures fields

- client/src/commons/NumericTextField/NumericTextFieldTypes.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/SearchCovidPatients/SearchByEpidemiologyNumber.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/SearchCovidPatients/SearchByPersonalDetails.tsx
> added keydown handles to contacted person search

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureFormStyles.ts
by einat's request - changed the select to be outlined instead of regular to match the form
> added border outline to filter select

- server/src/ClientToDBAPI/ExposureRoute/mainRoute.ts
problem was that sometimes airline was sometimes sent as a string and not an object - added an exception to catch it
> added handling for airline as a string

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
just added a pre filter to weed out empty contacts before comparing lengths
> added pre-map filter for duplicate contact validation

- client/src/commons/CustomSwal/useCustomSwal.ts
> removed icon from error alerts

- server/src/ScriptRunner/Scripts/index/BLK_admin_investigations_function.sql
Fix to bug: [1889](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1889)
changed function to filter by creation date instead of start date
> 1889/fix/filter-by-investigation-creation-date 

- client/src/logger/logger.ts
- client/src/models/Logger.ts
- server/src/DBService/config.ts
- server/src/Logger/Logger.ts
This reverts commit 2cc8bd35689c8c23371f87cfde158b74e1b016c3.
> Revert "log level (#2026)"
