- client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
- client/src/commons/AlphanumericTextField/AlphanumericTextFieldTypes.ts
This pull request contains an alphanumeric text field (can only accept letters, numbers and spaces). There is no usage to this component yet; it will be used with `react-hook-form` so these changes have no immediate effect.
> feat(forms) Create alphanumeric text field

- client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
i set the default value of an alphaNumericTextField to empty string to solve the problem that in first use is allowed to write forbidden signs.
> fix(regex-first-input): set default alphaNumericTextField value

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
Fixes bug [402](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/402/)
* An empty string ("") in person Id field will be sent as null => validation schema will approve it (nullable)
> Fix(person ID validation)

- client/src/commons/TypingPreventionTextField/TypingPreventionTextField.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
Solves bug [410](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/410/)
*Triggers validation when entering a non-valid form
*Removes Tooltip popup on error in Alphanumeric/Alphabetic text fields
(for the moment both Interactions Tab and Contact Questioning Tab can't be non-valid will be changed in the future)
> Fix(trigger validation) - When entering a non-valid tab the problematic fields will be marked

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/HospitalFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/IsolationProblemFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
Replaced `test-id` with `testId`, this is correct name for the attribute for `AlphanumericTextField`.
> Fixed missing test Ids in AlphanumericTextField

- client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
fixes bug [635](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/635/)
you may change the value only by using the autocomplete feature and select your new value from the options 
(as an autocomplete should work)
> fix(city-autoComplete) - Typing new value in city autocomplete will change current value to null

- client/package-lock.json
- client/src/Utils/axios.ts
Currently almost all the axios requests cause a setIsLoading call which impacts the performance of the project. This PR enables the option to use the default axios object to perform requests without calling the setIsLoading function. Eventually the axios instance will be removed when there will be better handling of loading states in the project.
> feat(axios) defined default headers and base axios interceptor

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields.tsx
This fixes the issue of the other checkbox not being checked when it's in the symptoms array.
> fix(symptoms) remove duplicate controllers for same field

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
Show all users when desks filter is empty,
Fix option desk label for users list
[895](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/895/) [896](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/896/)
> fix(investigationTable-filter-desks) - Show all users when desks filter is empty

- client/src/logger/logger.ts
- client/src/models/Logger.ts
- server/src/Logger/Logger.ts
- server/src/Models/Logger/types.ts
This PR adds a new way to write logs with less boilerplate by defining initial log data and then writing logs with only step and severity.
The new syntax will be:
```javascript
const occupationLogger = logger.setup({
workflow: 'Fetching Occupations',
user: userId,
investigation: epidemiologyNumber
});
occupationLogger.info('launching occupations request', Severity.LOW)
occupationLogger.warn('maybe something wrong', Severity.MEDIUM)
occupationLogger.error('Something failed', Severity.CRITICAL)
```
> feat(logger) add option to setup logger with initial params

- client/src/Utils/Routes/Routes.ts
- client/src/components/App/AppToolbar/useAppToolbar.tsx
- client/src/components/App/Content/Content.tsx
due to easy-auth documentation:
> feat(logout): redirect to login screen when you logout

- client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionsTab.tsx
In the interactions tab, there was a tab form that was responsible of moving tab when it is valid, and one of his children was another form that was the dialog of creating/editing event.
In this PR I moved the parent from being a parent, because this situation isn't right and creates unnecessary submits.
> fix(events): moved the tab form from being the dialog's form parent

- .github/dependabot.yml
This PR adds a depndabot.yml config file for automatically creating PRs for dependency updates.
Currently the process of updating our dependencies is dependent on our own discipline which is not enough considering we have two different package.json files (client/server) with many dependencies in each of them.
Dependabot™ is a github app bot which watches our package.json files and creates PRs when new versions of dependencies are available.
* Create `dependabot.yml` file in `.github` directory which updates npm packages daily.
> Add Dependabot™ to the project

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/useInvestigatedPersonInfo.ts
- client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
a problem that happened after changing county/investigator/desk in investigations table
what we did to solve this problem:
* remove unnecessary axios interceptors in investigation table that caused the problem 
(set is loading = true and never make it false).
* remove unnecessary timeouts after sweet alert  and use then after the alert instead.
> fix(unnecessary-is-loading): infinity spinner after changing county

- client/package-lock.json
- client/package.json
Reverts CoronaTeamMOD/CoronaInvestigation#884
There are type errors being caused by this version of react-hook-form that needs to be investigated further.
> Revert "build(deps): bump react-hook-form from 6.8.4 to 6.12.2 in /client"

- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
The logs of these methods were connected to different epidemiogical numbers, due to wrong paramter that was passed to the log messages
> fix(): use the current epidemiologyNumber on logs

- client/src/components/App/AppToolbar/AppToolbar.tsx
- client/src/components/App/AppToolbar/useAppToolbar.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- now pages refreshes and reroutes don't reset the filters applied to the investigation table
(new tabs **do** reset filters)
> feat(main table) save filter values on refresh

- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
This PR fixes the condition for not creating a new color for a group that was already assigned one.
> fix condition for not overriding existing group colors

- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
This PR fixes the issue with infinite loading after leaving investigation. This was caused by two things:
1. The setIsLoading being called before checking whether the user is logged in.
2. The broadcast channel calling the fetchTableData from the past where the user wasn't logged in yet.
* Make broadcastChannel to re-listen to onmessege on re-render.
* Call setIsLoading after checking whether the user is logged in.
> fix() change broadcast channel to re-listen on re-render

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationMenu/CommentDialog/CommentInput.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableStyles.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
* Make the investigation comment input border go red in case that the user enters more than the 500 characters in the comment
* hide the loading spinner in case that the fetching investigation process has been failed due to some reason
PS: hid the loading spinner not in finally block because it has been hidden before the investigations have been displayed
> fix(): fix error comment indication and remove spinner in case of investigation fetch error

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
Currently the dev doesn't work because the functions getCountyMapKeyByValue and changeCounty were removed in #971 but not removed from the useInvestigationTableOutcome  interface.
> removed unnecessary function from useInvestigationTableOutcome 

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
the save all function accidently sent the state (that it received) instead of the form's state causing the form's values to reset
connected the form state (instead of the general state) to the sending function
> fixed save-all function

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationInvestigatorSchema.ts
* The text for transfer reason is not required for all the investigations' transfer
* It makes admin investigators to write some garbage text for no reason just to be able to make it.
* Remove the 'required' enforcement to be able to transfer an investigation without reason when you don't have one.
> feat(transfer reason): remove required reason

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorAllocationDialog.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
Fix for bug #1273:
Seems each render of InvestigationTable fired fetchAllCountyUsers() function. now this function is fired when 
nvestigatorAllocationDialog is open. Also, I removed the call for this function when fetching investigation - it seems not in need anymore.
Now app runs a bit faster :)
> fix(users): fix multiple request call for investigator list

- client/src/commons/AirportTextField/AirportTextField.tsx
- client/src/commons/AirportTextField/AirportTextFieldStyles.ts
- client/src/commons/AirportTextField/AirportTextFieldTypes.ts
- client/src/commons/AlphabetWithDashTextField/AlphabetWithDashTextField.tsx
- client/src/commons/AlphabetWithDashTextField/AlphabetWithDashTextFieldTypes.ts
- client/src/commons/FlightNumberTextField/FlightNumberTextField.tsx
- client/src/commons/FlightNumberTextField/FlightNumberTextFieldTypes.ts
- client/src/commons/InternationalCityTextField/InternationalCityTextField.tsx
- client/src/commons/InternationalCityTextField/InternationalCityTextFieldTypes.ts
- client/src/commons/TypingPreventionTextField/TypingPreventionTextFieldTypes.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/AirportInput/AirportInput.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/FlightsForm/FlightsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Schema/flightsValidation.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/TransportationForms/FlightEventForm.tsx
1. the display of the flight dates (for bug [1302](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1302/))
2. fixed the required fields on exposures to be as supposed to be (for bug [1301](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1301/))
3. fixed the validations regexed as supposed to be (for bug [1303](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1303/)). I did it by creating new preventing text fields to airport, international city and flight number. I used that text field in both export and interaction event form
> fix(exposures): fixed validations and display

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumn.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationStatusColumn/InvestigationStatusColumnStyles.ts
fixes bug [1060](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1060/)
removed class `marginStatusWithoutIcon`
I'm still not sure as to why this class existed in the first place (as the flex and align-items proprety were being used horizontally)
centered all of the status's cells so they would appear like all of the other cells
> centered statuses

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
fixes the 'black box' issue at the investigation table ([1334](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1334)
issue was the Tabindex={0} part - it used the user agent stylesheets for tabindex:focus (which is a black border)
moved the 'escape' key listener to the window instead of the div
> removed 'tabindex' and added eventListener insead

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo/ReachContact.tsx
issue was that the `{...params.InputProps}`  overrides the default value of the field
fixes [1355](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1355)
> Fixed empty value issue in contact questioning

- client/src/Utils/DateUtils/formatDate.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/useExposureForm.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/InvestigationInfo.ts
dates are being sent from the API in ISO format (e.g. "2020-11-19T20:00:00.000Z"), those dates are later being formatted to a Date object by JS's new Date() function,
JS's Date() constructor **rounds** those datetimes to dates so "2020-11-19T20:00:00.000Z" now becomes "2020-11-20T00:00:00.000Z" which is displayed in the entirety of the project ( 😱 )
instead of rounding , I've added a pre-emptive floor to the date (by using .split('T')[0]) and then formatting the date, and added a ceil to the search (so in this example searching from  2020-11-20T00:00:00.000Z instead of  2020-11-19T00:00:00.000Z)
fixes [1340](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1340/)
> accurate coronaTestDates

- server/src/ClientToDBAPI/ClinicalDetailsRoute/mainRoute.ts
- server/src/Utils/addressUtils.ts
With the addition of #1115 the state of an empty isolationAddress  was { city : '', street : '' , floor : '' , housenum : ''}
the problem was that in the Address table the fields city and street were nullable and had FK constraint to their respective table.
added a new formatting function `formatToNullable` that takes those fields and formats empty fields to nulls
reasoning is that now the form is a generic components and this is the only exception where those fields need to be either nullable or FK.
fixes [1372](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1372/)
> Fixed error on empty fields on /saveClinicalDetails

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationIndicatorsColumn/SelfInvestigationIcon/SelfInvestigationIcon.tsx
Fix to: [1368](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1368/)
Now when toolTip opens when you click on it you get transferred to the investigation page, after fix when you click the toolTip get closed.
> Fix(self-investigation-icon-toolTip):make icon toolTip not clickable

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningInfo/ReachContact.tsx
continuing #1113 it appears that _sometimes_ the contactStatus state is empty when the object is initialized - leading to an `undefined` value that is moved on to the form value and messes up the form's state.
added an exception to catch the undefined value and added a temporary "loading" value
> fixed null contact statuses

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
fixes [1385](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1385)
the issue was that because of  #1115  all of the fields were set to null if they weren't disabled
removed the exception and re-formatted it to run only once.
> fix/blank isolationAddress Fields 

- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureForm.tsx
fixes [1408](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2013?workitem=1408)
> added optional covid patients reset when search query is empty

- client/src/commons/SearchBar/SearchBar.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooterInterfaces.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/useInvestigationTableFooter.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorAllocationDialog.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorsTable/InvestigatorsTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
This PR implements the following feature [1403](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1403/)
In this PR I added searchBar to the InvestigatorAllocationDialog component, also fixed existing bug that caused the popup Dialog to open twice and change the selected row to be chosen according to investigation id instead of rowindex.
> Feat(search-investigator):add searchBar on InvestigatorAllocationDialog

- client/src/commons/statusToFilterConvertor.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/PostponedCard/PostponedCard.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/PostponedCard/PostponedCardStyles.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/UnallocatedCard/UnallocatedCard.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/UnallocatedCard/UnallocatedCardStyles.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/adminLandingPage.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/useHoverStyles.ts
- client/src/models/FilterRulesVariables.ts
- client/src/models/InvestigationStatistics.ts
- client/src/models/enums/FilterRulesDescription.ts
- client/src/models/enums/InvestigationSubStatusCodes.ts
- server/src/DBService/LandingPage/Query.ts
Added a new card that lets an admin to access investigations table with transfer request or waiting for details filters (sub status filters) - US  [1285](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1285/)
> Feat(postponed investigations card): Add postponed investigations card in admin landing page

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
Fix to Bug: [1491](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1491)
Added ternary operator to control tooltip message according to the investigation/s selected.
> fix(tooltip-grouped-investigation-message)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/ContactsForm.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/AccordionContent.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/ContactsTable/ContactsTable.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/AccordionContent/ContactsTable/TableRows/TableRows.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/ContactsForm/InvestigationAccordion/InvestigationAccordion.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/ContactsSection/GroupedInvestigations/GroupedInvestigationForm/GroupedInvestigationForm.tsx
- client/src/components/App/Content/InvestigationForm/useGroupedInvestigationContacts.ts
- client/src/models/GroupedInvestigationContacts/ConnectedInvestigationContact.ts
- client/src/redux/GroupedInvestigations/GroupedInvestigationsType.ts
- server/src/DBService/ContactEvent/Query.ts
by user story : [1445](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1445) added filtering of family contacts only in case that the grouping reason is family members.
the reason I've added the isGroupReasonFamily at the form level is the same reason I've added the investigations - I wanted the logic (from redux) to only be applied once at the root instead of every time in the branch level
> added family filtering depending on grouping reason

- client/src/commons/Forms/AddressForm/AddressFormStyles.ts
fixes [1461](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1461), reason was that Material-UI's fields were getting their heights from px padding and height attributes - so to perfectly match them on empty fields I had to use static px size.
> moved minheight to px

- client/src/Utils/ControllerHooks/useExposuresSaving.ts
- client/src/commons/Contexts/ExposuresAndFlights.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/Forms/ExposureForm/ExposureForm.tsx
Fix to bug: [1453](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1453)
When saved the source was taken from the form data, and when source was deleted there wasn't a call to save the null value in the form data.
> fix(exposure-source-detail-dont-delete)

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
fixes [1490](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1490/)
problem was that isLoading was set to false on deleteIrrelevantContacts success and then immediately set to true in saveClinicalDetailsToDB.
something about the speed of the action probably caused the page to not show the loading sign the second time
made isLoading(false) only occur on failure (the function doesn't have any other uses)
> removed setloading(false) on success of deleteIrrelevantContactEvents

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
fixes [1484](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1484/)
#1272 solved half of the problem - what was happening is that when the investigation was being transferred `fetchTableData()` and `fetchInvestigationsByGroupId()` were running in parallel - both using global 'isLoading' - meaning that if both started at the same time - the one that was the quickest would have caused the loading to stop (even though the other one was still on-going)
so I changed the order of those actions to sync - first of all  `fetchInvestigationsByGroupId` runs in parallel on all of the group ids and when its done `fetchTableData` is run.
this also solved the problem of changing multiple grouped investigations loading (by the footer).
> moved loading of groupedinv order to sync

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorsTable/InvestigatorsTable.tsx
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
- client/src/models/User.ts
- client/src/redux/User/userReducer.ts
- db scripts/get_investigator_list_by_county_function.sql
- server/src/Models/User/User.ts
This PR implements feature: [1502](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1502/)
Major changes:
* changed DB function get_investigator_list_by_county_function to return the new information about user authority.
* changed the text on the source organization to include authorityName.
view:
> Feat(add-authority-display-name-investigators-table)

- client/src/Utils/GroupedInvestigationsContacts/getGroupedInvestigationIds.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/useInteractionsForm.ts
fixes [1506](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1506/)
the bug says that a user inserted 2 identical ids for the same event - after checking with @MagusM It looks like this was done on purpose as the log are looking reasonable (timestamp is normal - no close api calls)
the problem was that when the form was created it was possible to insert 2 identical IDs ( because the duplicate ID check was referring to the investigation's _existing_ ids)
with the addition of grouped investigations contacts this was becoming more of an issue ( as they could choose one grouped id and also add it manualy)
added a check in the form's state before sending - if the form/the connectedInvestigationForm already exists - alert the user and prevent him from sending the form
> added duplicate id check for form values

- server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
fixes [1507](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1507/)
the issue stemmed from  #1222 , in mainRoute the function missed all of the fields marked in red here :
because it only used spread `investigationPatient.covidPatientByCovidPatient`
added those fields back and removed `convertedCovidPatient.covidPatientByCovidPatient`
> fix/static investigation info - missing fields

- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields/SymptomsFields.tsx
Fix Bug: [1503](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1503)
The symptoms start date was sent with time and not only date. And the calculation of datesToInvestigate wasn't right what caused the bug.
Changed the symptoms start date to save without specific hour.
> Fix(symptoms-start-date-value)

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
fixes https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1506/
the problem was that `checkDuplicateIdsForInteractions()` wasn't taking into account the existing form Id's 🤔 , added newIds to check
> added new Ids test to current investigation

- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
Fix to bug: [1543](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2014?workitem=1543)
Now ToolTip message works like this:
* Case 1: true value of (isVaccinated, isReturnSick or isSuspicionOfMutation) && value in (vaccinationEffectiveFrom, previousDiseaseStartDate, mutationName) -> ToolTip with the value
* Case 2: true value of (isVaccinated, isReturnSick or isSuspicionOfMutation) &&  no value in (vaccinationEffectiveFrom, previousDiseaseStartDate, mutationName) -> ToolTip with the noInfo value
* Case 3: false value of (isVaccinated, isReturnSick or isSuspicionOfMutation) &&  no value in (vaccinationEffectiveFrom, previousDiseaseStartDate, mutationName) -> no ToolTip value at all
> fix(static-fields-tool-tip-message)

- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactSection/Schemas/contactQuestioningClinical.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactSection/Schemas/contactQuestioningPersonal.ts
fixes [1560](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1560/)
removed required validation from the schema of identification_type and city - so that city only be required in the event of isolation
> removed 'required' from identification type

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
the allocation function did not work,
2 issues here : 
1. the previous function didn't take into account that when an investigation allocation occurs through the row itself it has a group ID but also it can have an epidemiology number, so I've changed the logic to **either** instead of or so that it would work with all selections
2. the funciton (in the server side atleast) required a transfer reason , added blank reason.
> re-ordered allocation structure

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/InteractionDetailsFields/InteractionDetailsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/RepetitiveEventForm/RepetitiveEventForm.tsx
Fix to bug: [1552](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2015?workitem=1552)
The ExternalizationForm appears in every repetitive event. 
After conversation with the product manager, it was decided that the ExternalizationForm will appear only in the default date that the event was created at.
> 1552/fix/externalization-private-house 

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableRow/CommentCell/commentCellStyles.ts
if a SINGLE 45+ CHARECTER LONG WORD were to appear as the comment then it would be cut out,
by the way , the ONLY word that ever exist that is anywhere near this length is the 45 letter word [Pneumonoultramicroscopicsilicovolcanoconiosis ](https://en.wikipedia.org/wiki/Pneumonoultramicroscopicsilicovolcanoconiosis), and I doubt any one will ever use it as it is a synonym for scoliosis,
by the way the longest word in Hebrew is only 19 characters long (וכשלאנציקלופדיותינו) so I'm glad to know were safe on this side
added `overflow-wrap : break word` to the comment field
EDIT: if the investigator is Icelandic he can write Vaðlaheiðarvegavinnuverkfærageymsluskúraútidyralyklakippuhringur which is 64 character long
> added break-word for long words in comment

- client/src/Utils/GroupedInvestigations/getColorByGroupId.ts
- client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
this is the first version of the UUID to color function `getColorByGroupId`,
the function relies on the 6 last digits of the UUID (3 hex codes) and 'squishes' them to not be to dark or light while still maintaining a _fairly_ balanced color distribution
> Group color revision

- client/src/Utils/GroupedInvestigations/getColorByGroupId.ts
This is just some random UUID's that were sent by MOH I've collected from Production : 
from what I'm seeing the UUID that MOH sends are probably a variation ([see more](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format)) of UUID 1 (which is HIGHLY insecure - because it reveals MOH's server's MAC address (00:50:56:84:25:5c probably (it's a [valid](http://sqa.fyicenter.com/1000208_MAC_Address_Validator.html) mac address))
but with UUID1 the first few digits are _farily_ random so I'm hoping that this method will prove itself somewhat effective
> matched color generating method to hash

- client/src/commons/NoContextElements/AlphanumericTextField.tsx
- client/src/commons/NoContextElements/AlphanumericTextFieldTypes.ts
- client/src/commons/NoContextElements/HebrewTextField.tsx
- client/src/commons/NoContextElements/HebrewTextFieldTypes.tsx
- client/src/commons/NoContextElements/IdentificationTextField.tsx
- client/src/commons/NoContextElements/NumericTextField.tsx
- client/src/commons/NoContextElements/NumericTextFieldTypes.ts
- client/src/commons/NoContextElements/TypingPreventionTextField.tsx
- client/src/commons/NoContextElements/TypingPreventionTextFieldTypes.ts
- client/src/commons/TypingPreventionTextField/TypingPreventionTextField.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningCheck.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningClinical.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactQuestioningPersonal.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/InteractedContactAccordion.tsx
This PR includes HUGE (10x from ~600ms/character to ~60ms!) performance boosts to ContactQuestioning.tsx
So the problem was rooted within the context - more specifically within `TypePreventiveTextField` and other uses of it
When a member is subscribed to the form context - it will always re-render whenever the context will change - **even if the item is wrapped inside a memorized field** - from what I can see - I think that that there are 2 major problems in  `TypePreventiveTextField` :
1. The `get` function -  to get the current field's appropriate error it takes all existing errors from the state and filters them until it gets the current fields one - this happends every time every field changed (formProvider)
2. The `setError/clearErrors` functions - these functions edited the 'error' …
> Contact Questioning Performance 

- client/src/commons/InlineErrorText/InlineErrorText.tsx
- client/src/commons/InlineErrorText/inlineErrorTextStyles.ts
- client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/BackgroundDiseasesFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetailsSchema.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/IsolationProblemFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields/SymptomsFields.tsx
- client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/useClinicalDetails.ts
- client/src/models/Contexts/ClinicalDetailsContextData.ts
**Note:** This PR currently contains only clinical details because possible exposures is still in debate..
added default 'null' values for some clinical details toggles - and 'required' validations and error messages
The accepts nullable error field and returns inline error message with the error (if it exists)
> Default values - tab managment

- client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
This is a weird case, which signifies how inherently flawed this whole page really is -
turns out there are place and sub-places codes, and also the places actual names (like the codes can mean education - school and the place name will be 'Gan Nahum high school')
it is important to know that some places do not have a placename (like private house) so in that case the name is determined by a function called generatePlacenameByPlaceSubType.
the problem itself stemmed from the fact that once a place already have a place name ( in the private house case with no way of editing it) then generatePlacenameByPlaceSubType will not run again because it already has a name.
to fix this i've changed the way the name is calculated to the following logic:
if the place is a named location ( if the …
> added isnamedlocation refrence in the name

- client/src/components/App/Content/LandingPage/InvestigationTable/InvestigatorAllocation/InvestigatorAllocationCellStyles.ts
before
after 
it just bothered me.
note that im using px and not vw because vw doesn't scale well at all ( the smaller the screen size the more noticeable the scale difference is
> added horizontal margin for investigator cell

- client/src/Utils/Contacts/useContactFields.ts
- client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/ContactSection/Schemas/contactQuestioningClinical.ts
didn't eventually go with it at a top level because yup's _then_ only addresses the fields at scope level
> added validation exception on isolationAddress

- client/src/components/App/Content/LandingPage/adminLandingPage/desksFilterCard/desksFilterCard.tsx
- client/src/components/App/Content/LandingPage/adminLandingPage/desksFilterCard/desksFilterCardStyles.ts
- client/src/components/App/Content/LandingPage/adminLandingPage/investigationsInfo/investigationInfoButton/investigationInfoButtonStyles.ts
This PR fixes admin landing page (more specificaly investigationInfo and desksFilter)cosmetic issues, the main point of resolution is replacing static 'height' with relative values (vh/vw) to a static min height (px) and a relative max height (vh/vw) - preserving the current ratios
example :
before (laptop screen size)
after
> Admin landing page css

- server/src/ScriptRunner/Scripts/index/delete_public_contacted_person.sql
Problem was that `delete_contacted_person_funciton` was deleting public.contacted_person (by contacted_person(id)) and then deleting public.person - issue is that now contacted_person can contain multiple instances of person so deleting person violates FK constraint.
moved into just not deleting public.person at all.
> changed delete contact to only delete contacted_person instead of person

- server/src/ScriptRunner/src/LoadingBar/generateLoadingBar.ts
> loading bar redo

- server/src/ScriptRunner/Scripts/index/update_contact_person.sql
fixes an issue where you couldn't have entered a prev. deleted family member.
> added conflict resolution to family contacts

- server/Dockerfile
look, I have no idea how it worked until now. 
ts-node existed as a DEV dep for 9 months now, but apparently Docker (maybe node:slim distro - ill look into that) doesn't natively support ts-node anymore, (that's my guess at least)
this is support to at the very least make the server execute
> added global install of ts-node

- client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
problem was that the ref was directed at the button and not the element that is overflowing... 👀 @Noam6421 👀
> changed ref to overflowing element
